### ISSUE TITLE
gesture selection window improvement

### ISSUE THREAD

**Issue by Pz1c** [Pz1c/WavingHands#104]
I think it would be better in the gesture selection to have the same order as in the main spell book, meaning show:
"Disruptions:
DPP
DSF
etc;

Damaging:

SD
etc;"

and when you already select a gesture like 'D' then we could have the order be alphabetically.
This will make it easier for Newbies to learn the spells and not feel like there are too many. Makes sense?

**Comment by Pz1c** [comment]
first strike)
![image](https://user-images.githubusercontent.com/5511791/134332527-d6e411a6-0794-4c1f-b1cf-1c3040848116.png)

**Comment by Pz1c** [comment]
second strike
![image](https://user-images.githubusercontent.com/5511791/134337334-20ef7333-5099-49dc-b4bd-2bf059bada4b.png)

**Comment by Pz1c** [comment]
and finally third strike)
![image](https://user-images.githubusercontent.com/5511791/134339274-a1e8d2f8-ddab-4b16-9b1b-4ba469becae4.png)

**Comment by Pz1c** [comment]
@Prulon  please check design

**Comment by Prulon** [comment]
@Pz1c 

looks like we had some miscommunication here.
I actually meant the previous screen and not this one.

But now that I look at it, and considering that we have this one for later 
https://github.com/Pz1c/WavingHands/issues/101

I think it will be best to just revert and cancel this ticket, and keep the sorting here and in the previous gesture selection screen by ABC

makes sense?
(sorry)

**Comment by Pz1c** [comment]
hm, I don't get it
you mean do  not split spells by type and just keep completed spell and uncompleted with ABC sorting?

**Comment by Prulon** [comment]
@Pz1c 
yes

**Comment by Prulon** [comment]
basically the idea is:
1. you can see the list by topic if you click the spell book in https://github.com/Pz1c/WavingHands/issues/101
2. when you pick a gesture you want to see things by ABC

**Comment by Pz1c** [comment]
done
change to ABC
remove subgroup title
