### ISSUE TITLE
Private duels

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#105]
Note: while there's no name the submit button should be disabled 
![image](https://user-images.githubusercontent.com/78275620/132061034-669c415e-2f74-4fed-844d-177bee913c85.png)

**Comment by Pz1c** [comment]
maybe add scroll list with all wizards in the middle of screen? there much free space

**Comment by Prulon** [comment]
I'm not so worried about the white space.
Adding a list will make you feel like you should pick from the list.

Later on we will change many of the modals to be floating and smaller, so that will be ok. For now it's more important to have the functionality, and keep it simple

@Pz1c

**Comment by Prulon** [comment]
If you like you can move it upwards and add an "autocomplete" dropdown, if you can make it look good. But not critical

**Comment by Prulon** [comment]
I will also create a new issue, with your suggestion, and we can do it later, so we don't delay 1.9.5 for this

**Comment by Pz1c** [comment]
first attempt, just ignore)
![image](https://user-images.githubusercontent.com/5511791/145219692-fccab765-a374-4261-858a-5fe6a6affba3.png)

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/145226025-b70cd784-9934-496e-8ed2-bb0a99b43f59.png)

**Comment by Pz1c** [comment]
@Prulon I suppose when start new private duel with level f or vf (according window from where we open this window) and send invitation to chosen warlock?

**Comment by Prulon** [comment]
Yep :)

**Comment by Prulon** [comment]
@Pz1c notice that the submit arrow should be vertically aligned to the center of the input box. Right now it too much up

**Comment by Prulon** [comment]
also the text size for "Invite a warlock by name" is too big. should be same size as the description text

**Comment by Pz1c** [comment]
@Prulon please check
![image](https://user-images.githubusercontent.com/5511791/145389251-ed6d6c0e-a833-423c-b968-21114824fb18.png)

**Comment by Prulon** [comment]
@Pz1c 
looks good. Only missing the placeholder text "e.g. Galbarad"
color #544653

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/145400112-d954e3da-2324-431c-b534-08463d58ee55.png)

**Comment by Prulon** [comment]
Cool, but placeholder text vertical alignment is not centered

**Comment by Pz1c** [comment]
hate text align) i try center it but it was too high)
I'll try fix it

**Comment by Pz1c** [comment]
aaaand finally fixed)
![image](https://user-images.githubusercontent.com/5511791/146558429-fea665ce-3f66-4512-abd3-d04901819d7a.png)

**Comment by Prulon** [comment]
Great :)

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/147218218-d15819d6-ef9f-4a02-951a-48556b499921.png)
