### ISSUE TITLE
Accept private duel

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#106]
![image](https://user-images.githubusercontent.com/78275620/132062061-0596f8fb-e4a3-4945-aac0-e95dae9eb75d.png)

**Comment by Prulon** [comment]
Correcting the image above:
The word for not accept should be Reject

**Comment by Pz1c** [comment]
but where should be button to open this window? or just appear when found invite?

**Comment by Prulon** [comment]
@Pz1c 
Good question.
If you have an invite for a private game, then the invite should show on the main game list, with a title:
"Challenged by <Galbarad>"

Clicking on it should open the modal

**Comment by Pz1c** [comment]
depend on #120

**Comment by Pz1c** [comment]
no problem, will be in next release
