### ISSUE TITLE
Fixes for 1.9.3

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#112]
@Pz1c looked at 1.9.3 looks great :)

5 things that I noticed:
1. Main spell book - the color of the titles was changed, and now you can't see the titles as separate color. The color should be: #0654C0. Also font sizes and paddings were changed. See https://github.com/Pz1c/WavingHands/issues/61

2. Gesture selection screen - the word "Spellbook" should be aligned to left, not right, and should have the color #0654C0

3. Review screen - When opponent has a monster (or is possibly summoning one), if you cannot set its target (because you didn't charm it) then it should not show in the review screen
4.  I cast CDPW/CPSD --> I expected to see in the review screen the targets for the Dispel and for the Magic Missile, but only saw "Left hand gesture" and "Right hand gesture" with no mention of spell or target
5. I tried to cast PSDD at your giant, but couldn't set its target (so had to do it from desktop)

**Comment by Pz1c** [comment]
1.
![image](https://user-images.githubusercontent.com/5511791/135095336-31740425-b6d5-4ec1-8f23-a05f85dfeead.png)
2.
![image](https://user-images.githubusercontent.com/5511791/135095875-eb8278fd-bef6-4774-923a-e73a843594b9.png)
3. should be fixed
4. should be fixed
5. should be fixed
all problems should gone in 1.9.3.1
