### ISSUE TITLE
UI of the main menu

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#113]
![image](https://user-images.githubusercontent.com/78275620/134796143-d081795a-dbe1-4307-8108-42112e9d8869.png)

Note: at this point we do not have the "Rules" section or the "Hall of Fame", we can add them in the future

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/136028148-8e7d175c-5dd4-449a-8ccb-72ae76e6575f.png)

**Comment by Prulon** [comment]
Nice!!!
