### ISSUE TITLE
Show player's score, and improve colors of game list screen

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#114]
Player's score, and better looks for the main screen

![image](https://user-images.githubusercontent.com/78275620/134807313-7f9c032f-2fe2-4db3-b308-11cff216d9a6.png)

![background2](https://user-images.githubusercontent.com/78275620/134807327-2cb64fd6-08fd-4bd5-a3bf-3bb9e2b471ef.png)

Score is just the elo score of the player.
Clicking it should show a modal like the regular blue modal that we have, with:
Title: <Warlock's Name>: Stats
Description: no description
Details:
Score: <elo>
Played: <number of games played>
Won: <number of wins>
Died: <number of deaths>

**Comment by Pz1c** [comment]
player's score moved to #120

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/136786114-ba5002ca-cc39-4044-bb3f-7926a6fe9ff3.png)
