### ISSUE TITLE
New game button not working

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#115]
When I click "New Game" nothing happens. It doesn't even show like it is clicking

**Comment by Prulon** [comment]
@Pz1c 
This is probably the top priority problem - seems like no way to open new games.

**Comment by Pz1c** [comment]
yep I'll prepare 1.9.3.1 ASAP

вт, 28 вер. 2021 о 15:59 Prulon ***@***.***> пише:

**Comment by Pz1c** [comment]
problem appear in case no one friendly game available in list 
will be fixed in 1.9.3.1
