### ISSUE TITLE
Review screen bug

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#116]
The review screen doesn't always show the spells that were cast.
For example, start a new game.
Do a WWP with one hand.
The review screen shows "Left hand gesture" instead of "Cast protection at default target"

**Comment by Pz1c** [comment]
are you choose Protection  spell on gesture choosing screen?

**Comment by Prulon** [comment]
@Pz1c you know what, I think I didn't, 
so the review should say:
"Cast default spell at default target"

**Comment by Pz1c** [comment]
chosen spell is underlined 
![image](https://user-images.githubusercontent.com/5511791/135099154-1e48fa3a-2ff9-4eb7-84a3-49b145a947f4.png)
![image](https://user-images.githubusercontent.com/5511791/135099278-cb27055c-31ce-459d-a761-3ac53adfc616.png)

**Comment by Pz1c** [comment]
oh you mean we need change text in case exists spells finished on this turn?

**Comment by Prulon** [comment]
@Pz1c yes.
If there's a spell that was finished then the text should be Cast default spell

**Comment by Prulon** [comment]
@Pz1c 
also notice that if the text is long then it sometimes breaks.
For example if you surrender you will see "SURRENDERING (P/P) - raisin" and then the end doesn't show

**Comment by Pz1c** [comment]
please move this problem into separate issue

**Comment by Pz1c** [comment]
main problem should be fixed in 1.9.3.1
