### ISSUE TITLE
Network issue

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#119]
Updated to latest  version 1.9.3.2
getting an infinite loader, that ends with Error:
"Network problem details:Socket operation timed out"

**Comment by Prulon** [comment]
It happened after trying to submit orders

**Comment by Pz1c** [comment]
please remember me, your android version is?

сб, 2 жовт. 2021 о 08:16 Prulon ***@***.***> пише:

**Comment by Prulon** [comment]
sorry, 
android version 9

**Comment by Pz1c** [comment]
Please check 1.9.3.3
Also looks like i found root cause
https://www.washingtonexaminer.com/news/millions-old-gadgets-could-stop-working-weird-reason-digital-certificate

**Comment by Prulon** [comment]
So far the issue didn't repeat

**Comment by Pz1c** [comment]
Are you applying some system updates?

нд, 3 жовт. 2021 о 22:50 Prulon ***@***.***> пише:

**Comment by Prulon** [comment]
I updated on google play. So far works fine

**Comment by Pz1c** [comment]
are you mean that v1.9.3.3 fix the problem?

пн, 4 жовт. 2021 о 09:39 Prulon ***@***.***> пише:

**Comment by Prulon** [comment]
Yes
