### ISSUE TITLE
Coming soon modal

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#123]
The text should be changed to:
Title: "Coming Soon"
Text: "Hey! this is not ready yet, wanna help?"
Details:
"Warlock's Duel is a free open source game, developed by the Spellcaster community. You can give us a hand, or just chat with like-minded people"

Anyways I think we should remove the "Top" line from the menu, because this one isn't coming any time soon, and there are too many lines there that are coming soon...

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/136330146-84c300fb-671b-4c84-ba3d-b37b62a05110.png)

![image](https://user-images.githubusercontent.com/5511791/136338548-64c1f831-23a8-4d25-b410-e287d5f76cca.png)

**Comment by Pz1c** [comment]
doh again this typo)
thanks fixed already
