### ISSUE TITLE
Chat / History fixes

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#130]
1. Chat - show message and enable deleting (see image below)
2. Chat - font size, should be same as in the Turn History, see image below
3. Chat - the input square design is not the same as in the image (border color, corners)
4. Turn history - should not show "Say" messages, because these show in the chat history.
5. Turn history - reverse the order, so the last turn shows first

 ![image](https://user-images.githubusercontent.com/78275620/138581443-d4739721-8c89-4035-b7e2-240cb3fef73c.png)

**Comment by Pz1c** [comment]
@Prulon  please check)
![image](https://user-images.githubusercontent.com/5511791/161240995-eb8efa70-1d6a-48ec-b8bc-92b568e7b14a.png)

**Comment by Prulon** [comment]
Nice but the input box should be emptied.
The flow is like this:
1. Starr: input empty, message empty
2. Type "new cool" : meggage still empty
3. Click send: input gets empty, message="new cool"

**Comment by Pz1c** [comment]
doh, miss that((
push 1.9.7.4 to release already(
fix this problem in 1.9.7.5

**Comment by Prulon** [comment]
No problem, amazing progress!!!
