### ISSUE TITLE
Free discussion

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#132]
Wanted to share:
30d average of Google Play visitors, went up about x3 from ~4 to ~12, following the July updates to Store listing to capture more keywords
![image](https://user-images.githubusercontent.com/78275620/139492141-13d98a2a-692a-4681-9709-428d7d86b802.png)

**Comment by Pz1c** [comment]
oh, it's great
also I saw a little bit more warlocks in active user list

**Comment by Prulon** [comment]
yep, 
seems like one of them is waiting for someone to join his game ("Crisis") - I took one, you may wanna take this one :)

**Comment by Pz1c** [comment]
I saw search "warlock of firetop mountain" maybe we should add this keywords? cause Spellcaster was email based game with such name 
@Prulon  what do you think?

**Comment by Pz1c** [comment]
my coworkers ask for some game instruction  
https://www.youtube.com/watch?v=PThPw6quKZo

**Comment by Prulon** [comment]
Nice :)
the 3 new ratings are you coworkers?

**Comment by Prulon** [comment]
@Pz1c the search for firetop mountain is for a different adventure game called warlock of firetop mountain.
I can add in a few weeks, because now it will break the running test

**Comment by Pz1c** [comment]
oh I suppose it was firetop mountain from description
https://games.ravenblack.net/rules/1/credits.html
