### ISSUE TITLE
Prevent accidental surrender

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#135]
When selecting the second hand 'P' show a warning message like the image below
![image](https://user-images.githubusercontent.com/78275620/141645566-bf662cd0-3386-42d5-ae59-1ef9d7388e00.png)

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/142382634-909cfc05-a33d-42c0-8b67-b469df9590ff.png)

**Comment by Prulon** [comment]
Nice :)
