### ISSUE TITLE
Remove email from sign-up flow

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#136]
Looks like there's a drop of 15-30% between install app, and start a new game.
I believe that at least some of it may be because of the need to put in an email, which we currently don't even use (because there's no "forgot password").

Let's just remove the email field from the signup flow.

**Comment by Pz1c** [comment]
email need for "on server" registration, but you are right I can generate some fake emails

**Comment by Pz1c** [comment]
oh no it's optional)
my fault)
just remove it

**Comment by Pz1c** [comment]
perhaps add some wizard name for beginners
or even generate all data automatically and give only "start battle"  button
but we need some profile window to allow user change name and pass later

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/144448099-1585545e-54d7-4658-8f4a-3eebf5715f2d.png)
