### ISSUE TITLE
Private Duels, autocomplete

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#138]
See 2 images below for default state and for autocomplete state.

**Default State:**
- List shows warlocks that were active recently, and have a similar elo to the player.
- Sort by elo (high to low).
- Show only warlocks that were active in the last 10d or so (Color #DD2200 in the [RB hall of fame](https://games.ravenblack.net/players?showidle=1&order=elo))
- Show 4 players above the player's elo, and 4 below his elo
- Do not show the player himself, because he cannot invite himself to a duel
- The "View More" action is for the future, don't do it yet, and it will link to the Hall of Fame
- At the right show each player's elo
- Clicking on a player will fill the autocomplete with his name.

**Autocomplete State** 
- After a player starts inputting text, run an autocomplete
- Show only names that match the autocomplete
- Sort by ABC
- Don't show elos
- Bold the prefixes of the names that match the autocomplete text.

![image](https://user-images.githubusercontent.com/78275620/144712743-64c372dd-6194-496f-b221-46010ccf168d.png)

FYI @Pz1c

**Comment by Pz1c** [comment]
suppose need some "active" indicator 
or show only warlocks active in last 3 days

**Comment by Prulon** [comment]
@Pz1c looks great!

3 comments:
1. The submit button doesn't work, for example click Eru - the submit should be enabled
2. Missing the word 'Suggested' - see in the screenshot in the original post, for the initial list only
3. You can add the 'view more' and link to hall of fame

**Comment by Pz1c** [comment]
should be fixed in 2.3.8
