### ISSUE TITLE
Game list fixes

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#141]
See 4 issues in the image below:
1. I won the first game vs. succat, but the icon shows R.I.P instead of victory stars
2. The title says "Succat" instead of "Won vs. Succat"
3. The second game shows Battle #86722 finished" instead of writing who I played with and who won
4. The line before the last says "Won vs. " and doesn't say who I won against

![Screenshot_20211205-120941](https://user-images.githubusercontent.com/78275620/145430546-786a7f81-d24d-43ba-9307-284a59f5a05b.jpg)

**Comment by Pz1c** [comment]
should be fixed already
