### ISSUE TITLE
End game fixes

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#142]
See 3 issues in the image below:
1. Title doesn't say who I won against
2. Missing subititle to say what happened at the end e.g. "Prulon is victorious"
3. The game history ends in the middle, and you don't see the end (and can't scroll)
4. BTW - it may be better to sort from last turn to first turn

![Screenshot_20211205-121043](https://user-images.githubusercontent.com/78275620/145431188-dd2fda60-3a4e-4a58-b06a-87733c4836c8.jpg)

**Comment by Pz1c** [comment]
during End of Battle bug fix also fix problem with battle Waiting To Start
@Prulon  please check small fixes
![image](https://user-images.githubusercontent.com/5511791/160236981-186b3513-d493-423d-8fd1-a05d79f8e98e.png)

**Comment by Prulon** [comment]
@Pz1c In the app all games are ParaFC and Maladroit (to avoid making things too complex.
So I think it's better to write:
Title: "Waiting to Start"
Description: "Multi player game for 5 players"
"Warlocks accepted: Galbarad, Dubber, Aclosvz and you.
Waiting for 1 more warlock(s)"

**Comment by Pz1c** [comment]
please check
![image](https://user-images.githubusercontent.com/5511791/160247507-ca043de7-bff8-4916-b681-c1a71fccc477.png)

**Comment by Prulon** [comment]
Looks great :)

**Comment by Pz1c** [comment]
fixed finished battle window
![image](https://user-images.githubusercontent.com/5511791/160273846-b1f9d887-0538-4a73-a586-11d75b78fb1e.png)

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/160274288-8e052957-7269-4480-a012-f86fbe6dd8fc.png)
starts fixed too
