### ISSUE TITLE
Spellbook levels

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#143]
The goal of this task is:
1. To make the game simpler for beginners
2. To give incentives to play more games for new players.

Tasks:
1. Change the color of the spellbook title to #10C9F5
2. Change the title according to spellbook level (see details below)
3. Add a subtitle saying "Note: Small caps like 'c' indicate gestures that need to be performed with both hands". Font size 21 (in the image below it is too big). 
4. Limit the spells shown, per the table below, according to the spellbook level
5. Show a note at the bottom according to the spellbook level
6. In the gesture screen update the title to the relevant spellbook level (same as above)
7. In the gesture screen only show spells relevant to the spellbook level
8. In the spell selection screen only show spells relevant to the spellbook level

![image](https://user-images.githubusercontent.com/78275620/145444288-f0b00513-7b77-4f7f-8a30-f14ae163746d.png)

Spellbook level 1:
**Name**: "Spellbook: Apprentice Level 1"
**Spells (10 spells plus surrender and stab):** DPP,DSF,SWD,WFP,SFW,>,P,p,WWP,cw,WPFD,SD
**Hint**: "Stay alive for at least 15 turns to unlock spellbook level 2!"
**Unlock next level**: after the warlock reaches turn 15 in any game

Spellbook level 2:
**Name**: "Spellbook: Apprentice Level 2"
**Spells (10 more spells, charms, cures, counters, monsters):** PSDF, PSDD, PSDF, DFW, DFPW, FFF, WWS, WPP, FPSFW, WFPSFW
**Hint**: "Win a training game to unlock spellbook level 3!"
**Unlock next level**: after the warlock wins a game vs bot or player

Spellbook level 3:
**Name**: "Spellbook: Apprentice Level 3"
**Spells (10 more spells, damage, invi and more)** DFFDD, FSSDD, WDDc, SPFP, cDPW, PPws, DFWFd, DWFFd, DSFFFc, PDWP
**Hint**: "Win 2 more training games to unlock spellbook level 4!"
**Unlock next level**: after the warlock wins 2 more games vs bot or player

Spellbook level 4:
**Name**: "Spellbook: Warlock Level 4"
**Spells (6 more spells, elementals)** cWSSW, cSWWS, WWFP, SSFP, SWWc, WSSc
**Hint**: "Win at least 1 game against another warlock to unlock the Master Warlock Spellbook!"
**Unlock next level**: the player has at least 1 win (even if didn't complete the previous levels)

Spellbook level 5:
**Name**: "Master Warlock Spellbook"
**Spells** : all spells
**Hint**: no hint
**Unlock next level**: no next level

**Comment by Pz1c** [comment]
few proposes:
1. decrease 1 unlock from 15 to 10
2.  unlock 5 level when player win 5 vf battles because now we still not have a lot of newbie to fight each other and if newbie should fight with you for example to unlock 5 levels spell...

**Comment by Prulon** [comment]
1. cool
2. The goal here is to push people to start warlock vs. warlock games. So how about we change to "survive 15 turns or win in a warlock vs. warlock game"

**Comment by Prulon** [comment]
@Pz1c 
We can also add this when you receive the new spellbook.
1. It should be displayed after the modal of the game end
2. Clicking the button will open the spellbook
3. preferrably the icon will have an animation like scale up
4. the size of the icon is 256x256
5. the size of the spellbook name is 63, the size of the title is 42, the size of the text on the button is 42 (so spellbook size is 3:2 of title)
6. The color of the "Unlocked a new spellbook" is #0654C0, the color of the spellbook name is #10C9F5 the color of the button text is #A8F4F4

![image](https://user-images.githubusercontent.com/78275620/161283559-5e68683a-7afc-428c-9eb5-c98bebe625fb.png)

**Comment by Pz1c** [comment]
@Prulon  maybe we should put DFW on level 1?

**Comment by Pz1c** [comment]
part one done 
all windows filter spell by level
need to do
change player levels and show hint

**Comment by Pz1c** [comment]
maybe unlock 5 level when player only start battle against another warlock?
because win too hard achievement for newbie

**Comment by Prulon** [comment]
WE can do survive 15 turns against another warlock (or win).
Start seems loo little to me, and some people just start and dont play

**Comment by Pz1c** [comment]
should be fixed in 1.9.8
