### ISSUE TITLE
New game logic 

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#148]
The goal of this task is to make sure that people with elo >1700 can safely click "New Game", and to promote the app

Task:
When clicking "New Game" do the following:
1. Join a random Friendly ParaFC Maladroit game, but only if the elo difference is 200 or less (later we can put this number in settings), and only if you are not already playing with that same player.
2. If there's no such game available then create a new game, and put the following as title for that game:
"Created with android app Warlock's Duel. Elo <X> or more, please. ParaFC Maladroit."
where X is <elo -200>.

If X<=1500 then just write "Created with android app Warlock's Duel. ParaFC Maladroit."

**Comment by Pz1c** [comment]
@Prulon one of old app user change his review) and ask for maladroit/confuse mode
perhaps we should add more flexible settings for challenges
some day) in future)

**Comment by Pz1c** [comment]
now when player choose Random game against warlock added elo check
