### ISSUE TITLE
Add online indicator

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#150]
See below
For players that were online up to 5 minutes ago
font size 21 (regular font is 28, so this is 3:4 ratio)
color #2DA0A5 
capital letters, with italics

![image](https://user-images.githubusercontent.com/78275620/146173181-534055eb-9768-47e9-ba82-02371c1bcd42.png)

**Comment by Pz1c** [comment]
it's possible and easy

**Comment by Pz1c** [comment]
ok  just possible and not so hard)

**Comment by Pz1c** [comment]
dependent on #141 , #109

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/160631913-56421aa6-66d2-4eb3-a0d1-ef3b41206c3a.png)

@Prulon  please check

**Comment by Prulon** [comment]
Super!!!
