### ISSUE TITLE
Fix Delay Effect

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#151]
1. After delay effect is cast, when you cast a new spell and need to choose a target: Right now the delay keeps flashing. Instead should only flash once
2. When clicked, and selected it should have a cyan background color #A8F4F4
3. In the review screen right now the text is "Try bank spell casted by Left hand" instead it should be "Try to bank the spell cast by Left hand"
4 After a spell is banked, show the banked spell next to the "bank" (see image below)
5. When clicking on the bank or on the banked spell, both should be selected, with a background color #A8F4F4 instead of the current white border. In addition, write a toast saying "Banked <Amnesia> will be fired at <Galbarad>"
6. In the review screen write the same message
![image](https://user-images.githubusercontent.com/78275620/147142109-abf4201c-06fe-4057-89e4-bfdb290ea05c.png)
![image](https://user-images.githubusercontent.com/78275620/147142123-c7e93ccb-ea65-4a6e-ba16-31936c00b941.png)

**Comment by Pz1c** [comment]
1, 2 - fixed 
![image](https://user-images.githubusercontent.com/5511791/160637720-b20c20b1-7c72-436d-89f1-ee3f6aa3c76a.png)

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/160639035-5e6eea03-92a2-4832-a2e8-04becf296fa2.png)

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/160639213-b51622bf-d812-43ed-b83a-2f91cd5b4f4f.png)
what we should do if banked spell has no icon?
as Cure Light Wound for example?

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/160641658-b06927a9-f83f-4b98-bba2-6d579438c043.png)
this text from site

![image](https://user-images.githubusercontent.com/5511791/160641765-bcbc3dca-3906-4c76-9ebd-58af167f4f6a.png)

**Comment by Prulon** [comment]
Great :)
About your question - it's a great point. Here's my suggestion:
1. For spells with no icon we will not have another icon
2. When clicking on your own banked spell show the toast as I wrote above
3. When clicking on your opponents banked spell show a toast saying "Galbarad banked a <Magic Missle>"
@Pz1c

**Comment by Pz1c** [comment]
so you propose change banked icon "scroll with clock" to spell icon "Counter Spell" for example? 
so we will have only one icon as before
+ toast when click on icon?

**Comment by Prulon** [comment]
Yeah, I oropose to have only the backed scroll icon + toast

**Comment by Prulon** [comment]
3 more issues still exist with delay effect:

1. after yo click the hour glass to bank a spell and select a target and submit, you can not go back and select not to bank it. You will keep seeing in the review screen that you are "trying to bank ...". What I had to do to overcome this was to kill the app and restart

2. After banking, with default target, when you want to fire the spell the text is wrong. Right now it says "Banked will be fired at anti-spell"  Instead if should say "Banked Anti-spell will be fired at Default target"

3. We need to add one more thing - when selecting to bank a spell, the blinking is good, but it's still not clear enough what to do. So in this case let's change the default toast from "Choose a target ...." to "To bank a spell, click the the bank icon, and then choose the spell's target"

**Comment by Pz1c** [comment]
1.  uh, fix this ASAP
2. unfortunately I can show target for banked spell because server no provide this information (I can store it by my self in app, but it's not guarantied way)
3. ok

**Comment by Prulon** [comment]
about 2 - ok, so don't say target

**Comment by Pz1c** [comment]
should be fixed in 1.9.7.3
