### ISSUE TITLE
Releasing 1.9.5.2 to Google Play

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#161]
So @Pz1c do you think we can release 1.9.5.2 for general availability?

**Comment by Prulon** [comment]
@Pz1c 
would you like to publish 1.9.5.2 to Google Play, or do you prefer to wait for the notifications and release 1.9.6?

**Comment by Pz1c** [comment]
uh sorry I missed this issue
unfortunately I can't deploy 1.9.5.2 because app still in semi-disassembled state(
but I hope finish primitive notification at this week and move 1.9.6 to testing
