### ISSUE TITLE
Bots workaround

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#171]
If we can't fix bots then it may be best to have the "Start Training" open a regular ParaFC Maladroit Very Friendly game, and give  it the same title as we do for friendly games, and the same logic for joining a game as in friendly games.

Meaning "Start Training" will behave exactly like "Warlock vs warlock" except that the game will be Very Friendly.
What do you think?

**Comment by Pz1c** [comment]
I just completely removed AI logic from GUI so now I can try push AI to separated thread in main application 
so each player will be bot server as you plan at the beginning)

but we need some load balance - to much players with bots just break down ravenblack server)

**Comment by Pz1c** [comment]
perhaps AI will be work only for players that suppose interact with bot (start training battle or complete turn in bot battle)

**Comment by Pz1c** [comment]
unfortunately server owner do not want nether work on game, not opening source((

**Comment by Prulon** [comment]
What does this mean?
The bot is permanently dead?

**Comment by Pz1c** [comment]
nope it's about games.ravenblack.net site 
interesting why my mail answer not represented there(

**Comment by Prulon** [comment]
Btw, we can also limit the number of games you have with a bot, so if you
have an open game with a bot you will have to finish before moving on

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/160400515-a56b05c1-65f5-46d7-afab-6aeff45b8e5f.png)

**Comment by Pz1c** [comment]
hope this will b work under Android too)

**Comment by Pz1c** [comment]
hm unexpected crash((
looks like I am on the beginning  of large debugging adventure)

**Comment by Pz1c** [comment]
looks like fixed try build android version at the evening

**Comment by Pz1c** [comment]
most panful part of programming - environment setup(

should setup android build on new "build server"

**Comment by Pz1c** [comment]
Nope. It's about site owner
games.ravenblack.net
