### ISSUE TITLE
Fix "Waiting to start" texts

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#172]
If the game is for 2 players or against a bot, remove the line "Warlocks accepted: only you"

If the game is very friendly against a bot then the description should be:
"Training with a training bot"

If the game is very friendly against a single player then the description should be:
"Training with another warlock"

If the game is friendly against a single player then the description should be:
"Warlock vs. warlock"

**Comment by Pz1c** [comment]
are you mean changes in main window game's list?

**Comment by Prulon** [comment]
No, I mean on the modal that opens when you click on a waiting game.

**Comment by Pz1c** [comment]
should be fixed in 1.9.7.4
