### ISSUE TITLE
Question about backgrounds

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#177]
Is it possible to give a bit more of an animated feeling to the background by shifting continually between background.png and background2.png?
Here's an example that I found for animated background, except that here it is moving to the right, and I'd like it to stay in same position:
https://stackoverflow.com/questions/36894384/android-move-background-continuously-with-animation

Basically what I was looking for is that we would have:
background2.png as background, and on top of it background.png with a transparency alpha that changes from 0.0 to 1.0 and back.

**Comment by Pz1c** [comment]
yep, it's shouldn't be a problem
