### ISSUE TITLE
Fix text on private battles

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#179]
I invited Asgard12 to a private duel.
Right now the text says:
"Warlocks accepted: Asgard12 and you"
but Asgard did not accept yet.

Instead let's write:
"Warlocks accepted: only you"
"Warlocks challenged: Asgard12"

**Comment by Pz1c** [comment]
@Prulon  please check
![image](https://user-images.githubusercontent.com/5511791/161377659-51997505-3251-46ca-99ca-55ae92ec779c.png)

**Comment by Prulon** [comment]
looks good!

**Comment by Pz1c** [comment]
will be fixed in 1.9.7.6
