### ISSUE TITLE
BI events for game start and end

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#181]
Create the following flurry custom events: (https://developer.yahoo.com/flurry/docs/analytics/gettingstarted/events/android/)

All following events will have these params, and some have additional params
Param: "Type" values "Training" | "Scored"
Param: "With" values "Bot" | "Random warlock" | "Private warlock"
Param: "Id" value=game number
Param: "Warlock" value= name of warlock that created the game

Event: "Game_Created"

Event: "Game_Deleted" (when the warlock leaves the game)

Event: "Game_Started"
Param: "Players" value [Prioli, Galbarad,, ...]

Event: "Game_End"
Param: "Players" value [Prioli, Galbarad,, ...]
Param: "Winner" value: warlocks name or "draw"

Event: "Game_Pending_Clicked" (when a player clicks on a game, which has not yet started)

Event: "Game_Ready_Clicked" (when a player enters a game that is ready to play)

Event: "Game_Waiting_Clicked" (when a player clicks on a game that started but is in waiting mode)

Event: "Game_Finished_Clicked" (when a player clicks on a finished game)

Event: "Game_Turn_Submitted" (when a player submits orders for the turn
Param: "Turn" value = turn number

Event: "Game_Turn_Forced" (when a player clicks force turn)
Param: "Turn" value = turn number

-------------
The following don't have these special param
Param: "Mode" values "beginner" | "ready" (beginner is when we show "Start Training" as the main button)
Param: "Spellbook_Level" value = level of spellbook
Param: "Finished_Trainings" value = finished number of training games (we track it, right? to set the mode)
Param: "Finished_Games" value = finished number of games against other warlocks (do we track it? if not then ignore this)

Event: "ListGames_View" (wheneve the player lands on the game list screen)

Event: "ListGames_Refresh_Auto" (when the app refreshes the game list automatically)

Event: "ListGames_Refresh_Clicked" (when a player clicks refresh)

Event: "ListGames_Menu_Clicked" (when a player clicks on main menu)

Event: "ListGames_Spellbook_Clicked" (when a player clicks on spellbook)

Event: "ListGames_Score_Clicked" (when a player clicks on his own score)

----------------
Event: "Rating_View" (when we show the rating screen)
Event: "Rating_Click" (when the player clicks to submit a rating)

Event: "Feedback_View" (when we show the feedback screen)
Event: "Feedback_Click" (when the player clicks to submit a feedback)

----------------
Event: "Play_Left_Click" (when a player clicks on his left hand)
Event: "Play_Right_Click" (when a player clicks on his right hand)

Event: "Play_Gesture_View" (when a gesture screen shows)
Param: "Spellbook" value: level of spellbook

Event: "Play_Gesture_Spell" (when a player clicks on a spell in the gesture screen)
Param: "Spell" value: name of spell clicked

Event: "Play_Gesture_Click" (when a player clicks a gesture)
Param: "Letter" value: letter clicked

Event: "Play_Gesture_Submit" (when a player submits a gesture)
Param: "Letter" value: letter clicked

Event: "Play_CompletedSpells_View" (when a player views the list of spells to pick from)
Param: "Warning" value: none | surrendering

Event: "Play_CompletedSpells_Submit" (when a player submits a spell)
Param: "Spell" value none | default | spell

Event: "Play_Target_View" (when a player views list of targets)

Event: "Play_Target_Clicked (when a player clicks on a target)
Param: "Target" value = target's name

Event "Play_Target_Sumbit" (when a player clicks to submit a target
Param: "Target" value = target's name | default | none

Event "Play_Submit_Clicked" (when a player clicks submit to see the review screen)
Event "Play_Review_View" (when a player views review screen)
Event "Play_Review_Click" (when a player clicks on a review)
Event "Play_Review_Final_Submit" (when a player clicks submit from review screen)

Event "Play_Chat_Click" (when a player clicks on chat)
Event "Play_History_Click" (when a player clicks on history)
Event "Play_Spellbook_Click" (when a player clicks on spellbook)
Event "Play_Monster_Click" (when a player clicks on a monster)
Event "Play_Walrock_Click" (when a player clicks on a warlock)
Event "Play_Spell_Click" (when a player clicks on a spell)

Event "Play_FFF_Choose" (when a player chooses FFF for opponent)
Event "Play_PSDF_Choose" (when a player chooses PSDF for opponent)

Event "Play_Tutorial_View" (when a player sees an in game tutorial message)
Param "Text" value = the text shown

Event "Play_Tutorial_Click_Next" (when a player clicks next on tutorial)
Event "Play_Tutorial_Click_Back" (when a player clicks back on the tutorial)
Event "Play_Tutorial_Click_Gotit" (when a player clicks got it)

-----------------------
Event "MainFunnel_Start_Training" (when a player creates a first training game)
Event "MainFunnel_Submit_Turn" (when a player submits his first turn orders for the first time)
Event "MainFunnel_Submit_Turn_5" (when a player first submits orders for 5th turn, showing he understand how to send)
Event "MainFunnel_Training_Game_Ended" (when a player first finishes hist first training game, with at least 5 turns)
Event "MainFunnel_3_Training_Games_Ended" (when a player has finished at least 3 training games
Event "MainFunnel_10_Training_Games_Ended" (when a player has finished at least 10 training games
Event "MainFunnel_PvP_Game_Created" (when a player has started his first PvP)
Event "MainFunnel_PvP_Game_Started" (when a player starts his first PvP)
Event "MainFunnel PvP_Game_Ended" (when a player has finished his first PvP with at least 5 turns played)
Event "MainFunnel_3_PvP_Games_Ended" (when a player has finished at least 3 PvP games)
Event "MainFunnel_10_PvP_Games_Ended" (when a player has finished at least 10 PvP games)

**Comment by Pz1c** [comment]
Event "Play_Target_Sumbit" (when a player clicks to submit a target
Param: "Target" value = target's name | default | none

depend on #210
