### ISSUE TITLE
Improve UI of spell descriptions

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#189]
Why - 
right now the descriptions look frightening and unfriendly.
1. Update the spell description to look like the below
2. Colors: see in the image
3. Font sizes: Title and gestures (42), Short description (28), long description (21), back button (28) - our usual font sizes.
4. Spell icon : per spell. For spells that don't have an icon use the stars - [purple.png icon ](https://drive.google.com/file/d/1nRVR6EkCBOgri7VaYUPfUc9BIZUVONRn/view?usp=sharing)
5. Add an animation of scale up to the icon, like we have for the wizard spellbook level

![image](https://user-images.githubusercontent.com/78275620/164464248-9af7dc5c-adb2-497e-86c5-349445638083.png)

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/165381642-e9d33c36-5ba1-427e-9c88-8f8af7fd41fd.png)

**Comment by Pz1c** [comment]
one more variant
little bigger icon

![image](https://user-images.githubusercontent.com/5511791/165382091-97a1158d-b31e-427e-b148-fa8988ccbf5f.png)

**Comment by Prulon** [comment]
Big icon looks better

**Comment by Prulon** [comment]
Note that the font size of the long description should be smaller.
It should be 3:4 to the "Back" button and the subtitle, and 1:2 to the spell name
(I used 21 for long description, 28 for back and subtitle, 42 for spell name)

**Comment by Pz1c** [comment]
yep with 21 font size for desc much better
![image](https://user-images.githubusercontent.com/5511791/165538408-0ca9c436-bc23-4567-98fc-e9e5ebac4a02.png)
