### ISSUE TITLE
Small fixes for spell selection screen

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#190]
On the spell selection screen fix the following:
1. **When selecting the '-' no gesture**, right now the list shows the default spell. Instead it should say "Complete Spells" "None"
2. **UI fix** - increase the vertical space between the "Incomplete Spells" section and the section above it by 48px
3. **Clicking on an incomplete spell** - right now clicking on an **incomplete** spell closes the gesture selection window, and moves to target selection, which feels a bit strange. Instead it should open the description of that spell

**Comment by Pz1c** [comment]
should be fixed in 1.9.8.1
