### ISSUE TITLE
game over notification keeps showing

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#193]
For every game that ended we should only send an end game notification once, and that's it.

Right now I keep getting a game over notification, and can't get rid of it...

A simple solution might be to keep the last time in which we [sent any notification (e.g last_notification_date),  OR refreshed game list screen]
and send notifications only for things that happened after that time (so if the game ended before that time we wouldn't send a notification for it)

**Comment by Pz1c** [comment]
should be fixed
