### ISSUE TITLE
No blank gestures

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#194]
**Issue**
There's actually never any reason to use the '-' gesture. It is only confusing, especially for new players (saw this a few times when I showed the game), and leads to bad experience. The only reason ever to use that in the game is when charming the other player.

**Task**
Remove the '-' gesture, so players cannot select it.
Only show it as an option if casting charm person at opponent, so that you can choose the '-' as gesture

**Comment by Pz1c** [comment]
should be fixed in 1.9.8.1
