### ISSUE TITLE
No 'Default Spell

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#196]
**Issue**:
The idea of casting a default spell is confusing, especially for beginners, as I saw on several cases.
It's also not really needed, except if opponent cast a PSDF or FFF at you

**Task:**
1. Remove the option to select 'Default' spell. Always show only the real spells, and always select the default automatically for the user. For example if I have WWP then my options should be 'Protection' and 'Shield' and Protection should be selected
2. The only cases in which the 'Default' option should be there (and then it would be the one selected) are when opponent case FFF or PSDF at you

**Comment by Pz1c** [comment]
should be fixed in 1.9.8.1
