### ISSUE TITLE
No Default targets for spells

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#198]
**Issue**:
The use of the word default creates a bad unclear experience. It is better to always select actual targets

**Task**:
1. In every case in which the user is casting a non 'default' spell, which is basically always the case if the wizard is not charmed or under FFF, select, instead of choosing 'default' target when clicking next, chose the real target.
For example, if I am casting a shield - default target would be the caster.

2. The only case where default target will stay is for default spells like "Casting default spell at default target"
3. In all cases except when under charm or under FFF remove the option to select "Default" as a target.

**Comment by Pz1c** [comment]
looks like fixed
