### ISSUE TITLE
Change the order of spells in gesture selection 

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#199]
**Issue:**
Right now the alphabetical order of spells in the gesture screen makes is not very useful, it puts a lot of focus on non complex spells vs. beginner spells, and makes the game feel more complex.

**Task:**
The order right now is by: 
Count of matched gestures > Alphabetical

Change the order to be by: 
Count of matched gestures > Word length > Alphabetical

So for example, if **'SF'** are the gestures from last turns then now we will have:
**SF**W
**F**FF
**F**PSFW
**F**SSDD
'>'
P
cw
DFW
DPP
DSF
etc'

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/165152677-d46e93cd-838d-45b5-91fb-303a2bc8df76.png)

**Comment by Pz1c** [comment]
should be fixed in 1.9.8.1
