### ISSUE TITLE
Update the game end screen (similar to new spell description screen)

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#200]
See below.
Titles:
"Uh Oh... You lost the game."
"Yey! You won the game."
"Hmm... It's a draw."

Subtitle:
<Your player> vs. <Player>  (example: "Prulon vs. Galbarad")
<Your player> vs. <Player>, <Player>, <Player> and <Player> for multi player games (example: "Prulon vs. Galbarad, Dubber and Kenobi"

Description: 
Same as in the game end screen today, except no line break between the lines. E.g. "Galbarad is victorious! Prulon dies."

![image](https://user-images.githubusercontent.com/78275620/164944904-cb53fd3b-bd1b-42c5-b854-57787ba3f70d.png)

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/167306083-69483c38-9588-47b1-bfdf-c6213eb88d58.png)
little bit change titles to reuse spell window

**Comment by Prulon** [comment]
Great
