### ISSUE TITLE
Chat animation

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#201]
Do the following 2 fixes:
1. Do not show the pimple on the chat if the other player did not say anything, and only you did
2. If the other player did say something, and it is not a bot then show a small animation when opening the game, to highlight that there's a message waiting for you.

**Comment by Pz1c** [comment]
i suppose that we no need additional animation because we show chat message in "before battle animation"
@Prulon please check

**Comment by Prulon** [comment]
agree
