### ISSUE TITLE
Spellbook: Next spellbook level UI issue

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#207]
The next spell level text is long and goes beyond the box area. Instead we should break it to 2 lines of text.

**Comment by Pz1c** [comment]
@Prulon  may I ask for screenshot
can't catch problem(

**Comment by Prulon** [comment]
@Pz1c 

See image below.
My warlock is now level 3, so looks too long, but ok. In level 1 is even worse. We should break to two lines.
Also the text should be Bold
![Screenshot_20220505-132609](https://user-images.githubusercontent.com/78275620/166905921-7f4eb292-21c0-407a-aeac-c4a6cf49931f.jpg)

**Comment by Pz1c** [comment]
done
