### ISSUE TITLE
Make it easier to understand summoning

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#209]
**In the review screen** (see current state in the image below):
1. When you summon a monster, change the text from "cast Summon Goblin at default target" to "Summon Goblin to serve default target" etc'
2. also change the target text from "direct New Monster (R) at Daelazar" to "direct New Goblin (R) at Daelazar" using the name of the actual monster that you are summoning, except in the following 2 cases: 1) If the name is unknown because you are under Charm or FFF, and you are casting default spell then keep the current text. 2) Also when directing opponent's monster keep the current text.

New Monster icon
1. Change the icon for new monster according to the above to either "New Goblin" "New Ogre" "New Troll" "New Giant" or "Unknown Monster" (all images are the in regular [folder](https://drive.google.com/drive/folders/1Wpn_1bFBAskwzdg18ujxszpKRjk4lT-w?usp=sharing)). See also example of new icon for "New Goblin" below

**In the battle screen and in target selection screen** (see second image below)
1. Show the new monster icon only if: 1) you have completed a summoning spell. So for SFW show the icon, but for SFP or when didn't select yet SF_ do not show the new monster icon. 2) You are under Charm of FFF and opponent may force you to complete a monster 3) on opponent's side always show the new monster if the opponent may complete that monster

![image](https://user-images.githubusercontent.com/78275620/166102009-13c39fbb-611f-4e6e-a8d0-9628e953d181.png)
![image](https://user-images.githubusercontent.com/78275620/166102317-e8ea90e0-1619-4f15-be87-c19d619e49ee.png)
![image](https://user-images.githubusercontent.com/78275620/166108390-44e2e799-ae88-430e-92dd-ca28fb3d5df0.png)

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/172841284-3e6e390a-4dff-4f48-b754-c1414718af2e.png)

![image](https://user-images.githubusercontent.com/5511791/172841341-383901ba-f103-4043-9840-1bd1fc559afe.png)

![image](https://user-images.githubusercontent.com/5511791/172842249-d516d2fc-63ea-436e-b436-4bd41907d1f5.png)

small problem with align)
