### ISSUE TITLE
Improve experience of target selection

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#210]
Issue:
Following a usability test that I did I saw that it's hard to understand the targeting screen.

Task:
Update the screen like the image below, doing the following changes:
1. Remove the toast
2. Add a text saying, almost the same as in the review screen, except that a) add a ':' before the target b) use #10C9F5 as font color for the target c) if this is for permanency add suffix "(make permanent)", if for delay effect add suffix "(bank it)"
3. Add a cyan background to the selected target color #A8F4F4 see image
4. Add a new icon for "default target", the question mark. See image
5. Change the submit icon on the right as follows: 1) remove the background 2) add the word "Done" 3) clicking it does not change the target, only confirms the selection
6. Clicking on a new target will not close the screen, it will only change the selection

![image](https://user-images.githubusercontent.com/78275620/166105861-128d81d4-ab20-497a-8a18-327c0728d428.png)

**Comment by Pz1c** [comment]
in case of elemental all icons move to the right?

**Comment by Prulon** [comment]
Yes

**Comment by Prulon** [comment]
by the way, regarding item number 2 - we can actually take this version of text and put the same one also in the review screen, so it will be simpler to read also there.

**Comment by Pz1c** [comment]
add logEvent("Play_Target_Sumbit")
Event "Play_Target_Sumbit" (when a player clicks to submit a target
Param: "Target" value = target's name | default | none

**Comment by Pz1c** [comment]
@Prulon  we have little problem with text and icon
we have no space for all(
![image](https://user-images.githubusercontent.com/5511791/172717219-e7dcb1e6-2cb5-4626-922d-7ce0b19d3088.png)

**Comment by Prulon** [comment]
Can this work:
1. Hide the border line at the bottom
2. Overlay the new text in that location, aligned to center horizontally
3. Increase the size of the 'X' icon to be the same as for elemental
4 take the Done and icon upwards so the are aligned well with other icons

See image

**Comment by Prulon** [comment]
![Uploading Screenshot_20220609-083738_Gmail.jpg…]()

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/172813268-1c9e2882-3d2b-408d-8b7a-fead22fd41b2.png)

**Comment by Pz1c** [comment]
@Prulon  please check

**Comment by Prulon** [comment]
Looks much better, but the Done and arrow should be higher, aligned to
center of the X

**Comment by Prulon** [comment]
Also let's add background color to the text like this
1. added background color
2. moved the done upwards
![image](https://user-images.githubusercontent.com/78275620/172907308-e3fdc2ff-62a0-451e-aac0-641d3033d95f.png)

**Comment by Pz1c** [comment]
@Prulon please check
![image](https://user-images.githubusercontent.com/5511791/172932275-50be2b3c-5c82-4429-a136-435fdf7f7dbc.png)

**Comment by Prulon** [comment]
Great, if possible then add 6px of padding between the text and the icons
below

**Comment by Prulon** [comment]
@Pz1c 
Yes but also:
1. Keep a padding between gestures and text
2. Align the 'X' and the 'Done' to the vertical center of the area below the text - see image below

![image](https://user-images.githubusercontent.com/78275620/172998652-c7bdbf2e-9a44-400e-915f-b74dcd3beabc.png)

**Comment by Prulon** [comment]
I actually have a better suggestion  - can we do this?
![image](https://user-images.githubusercontent.com/78275620/172999647-2431e493-446e-4c45-9cb2-12dc0f90b73c.png)

**Comment by Pz1c** [comment]
I suppose yes)

**Comment by Pz1c** [comment]
@Prulon please check
![image](https://user-images.githubusercontent.com/5511791/173178820-0b9dc5cc-5f81-4feb-83ae-a7ffc0cf3e5e.png)

**Comment by Prulon** [comment]
Cool, let's just add 6px padding in the 2 places that I marked in the image below

![image](https://user-images.githubusercontent.com/78275620/173187228-88d95059-19c7-47e6-a807-4d3b569335ef.png)

**Comment by Prulon** [comment]
(I just move the 'X' and the 'Done' and the line a bit up

**Comment by Pz1c** [comment]
@Prulon please check (I hide line because Nobody button got on the line)
![image](https://user-images.githubusercontent.com/5511791/173200502-e7be0744-250f-42b9-8663-705342645184.png)
