### ISSUE TITLE
Make spellbook levels more clear on gesture screen

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#213]
Add a comment at the end of the gesture selection screen (see image below) - font 21, color #10C9F5. 
icon size is 32px. The text is the usual text for next spellbook level.

![image](https://user-images.githubusercontent.com/78275620/166109636-b5f4856c-f35f-43d9-99d8-374717904ddb.png)

**Comment by Pz1c** [comment]
@Prulon sorry I can't find lightning icon in 512x512 folder( only lightning_bolt with heart

**Comment by Pz1c** [comment]
@Prulon please check
![image](https://user-images.githubusercontent.com/5511791/167272237-d6c511f5-9517-4188-b61e-56c8e2b48473.png)

**Comment by Prulon** [comment]
Few notes:
1. The spell names should not be grey. They should be grey only in the
Incomplete spells list after you select a gesture

2. The new hint should come at the end of the spell list after scroll down
and not have a separate scroll section

**Comment by Pz1c** [comment]
@Prulon and new version)
![image](https://user-images.githubusercontent.com/5511791/167289069-4cb8cfec-2eca-4173-9aca-244d807e4f6a.png)

**Comment by Prulon** [comment]
This is good except that the text about the new level should not be
separated.
It should be part of same scroll on same background together with the list
of spells

**Comment by Pz1c** [comment]
uh ok)
done
