### ISSUE TITLE
Text fix for paralysis, for maladroit and for fear

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#214]
**Fear**: Change the spell title to be just "Fear" (remove the "no CFDS")
**Fear**: Update the spell title to "Opponent may only use 'P', 'W' or '>' gestures"
**Maladroit**:  remove the word confusion from the name of the spell in the gesture selection screen. It seems ok in other places.
Paralysis: Update the spell title to "Choose opponent's hand. Force it to repeat last gesture. Exceptions: 'F' turns to 'C', 'W' to 'P', 'S' to 'D'.

**Comment by Pz1c** [comment]
can't find any title with Confusion for DSF
@Prulon may I ask for example?

**Comment by Prulon** [comment]
@Pz1c 
About Confusion - 
Start a new training game, then go to the gesture screen to pick a gesture - you will see Confusion / Maladroitness

**Comment by Pz1c** [comment]
fixed
