### ISSUE TITLE
Change the new game modal

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#215]
Issue:
In usability and in player games I saw that players take a lot of time to discover the option of PvP and even then don't always start it. I saw in Zynga that all these options are usually in the same screen.

Task:

1. Right now, in the main menu we have 2 options "New Game" and "Start Training" (or for new players we have "Start Training" and "warlock vs. warlock". Change it so that the button always says "New Game" and there's no second option.
2. The Button will open the next modal instead of the existing ones. It's always the same modal
3. Clicking on "More options" will open the modal that we currently have when you click "start training"
4. The icons that I used are "single sword" and "stab" icons, in the folder. size 96x96 pixels.

![image](https://user-images.githubusercontent.com/78275620/166112983-386f7c79-3385-4a92-938e-046ed124537f.png)

**Comment by Prulon** [comment]
Let's change the text in the above from 'Smart Match" to "Auto Match"

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/172073536-a7fc93a9-7eeb-4809-bfc7-fdd8e212ff49.png)

**Comment by Prulon** [comment]
Wrong title on the second part - should say "A New Duel" not practice mode. 
Also ichane "Auto Match" to "Auto match"

**Comment by Prulon** [comment]
Let's change the "Auto Match" to "Play" 
Seems no one is clicking the Auto Match

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/208926122-b53fcfdf-2c6a-4773-b60a-3ea708d40230.png)
