### ISSUE TITLE
Simplifications for beginners

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#218]
1. When in spellbook level 1:
a) remove the 'cw' spell - (make it a level 2 spell)
b) make the 'c' gesture always disabled until you get to level 2

2. When playing against a bot:
a) remove the chat icon

3. When a spell is cast (like 'maladroit') add a small animation when it appears, so it's more clear that a new spell was cast

**Comment by Pz1c** [comment]
1,2 done and 3 will be done under #74 I'll do it in next milestone
