### ISSUE TITLE
Create tutorial for newbie

### ISSUE THREAD

**Issue by Pz1c** [Pz1c/WavingHands#22]

**Comment by Prulon** [comment]
Galbarad - see suggestion for tutorial in the screenshots (at the bottom.
This could go for the first game.
https://drive.google.com/file/d/1inB1WVvkmr8eyYqUAtIC0F8NwTxsVqU7/view?usp=sharing

Tutorial no.1
1. Every letter represents a gesture. A set of gestures like DPP is a spell (Amnesia)
2. Some useful spells: SD (Magic Missile) deals 1 damage. P (shield) will defend against it...
3. ...But P/P with both hands will make you surrender. (marked as lowercase 'p' in your spellbook)
4. Enchantments like DPP (Amnesia), DSF (Maladroit), SWD (Fear) disrupt your enemy
5. When two are cast at the same Warlock they cancel out.
6. Check your spell book to learn more spells...

You can do similarly more tutorials later on one per game like these:

Tutorial no.2
1. Summon a goblin (SFW) to fight for you. Cast it on yourself, and then set its target. 
2. Stab ('>') is a simple way to hit a goblin. Shield ('P') and Protection (WWP) to defend.

Tutorial no. 3
1. Inflict direct damage with Cause light or heavy wounds (WFP, WPFD)
2. Heal up with Cure (DFW, DFPW)

Tutorial no.4 
1. There are two ways to counter a spell (WPP, WWS). 
2. Cast them at yourself to prevent spells and monsters from hitting you. 
3. Cast at an opponent to prevent him from summoning a monster.

Tutorial no.5
1. You're doing good! Keep up. 
2. After you get a bit more training you can start playing against other players and friends.
3. Games with other players are played in turns. 
4. You can play up-to 3 games at the same time for free
5. You've got up to 3 days to play each turn.

Tutorial no. 6 
1. When playing against real players, you'll be seeing a lot of these spells...
2. ...Charm Person (PSDF) to force a gesture (or a no gesture '-')
3.  Charm Monster (PSDD) to take control of a monster, and change its target
4. Conceal movements with Invisibility (PPws) - lower caps means w/s with both hands

Tutorial no.7
1. Summon stronger monsters in addition to Goblins (SFW)...
2.  like Ogre (PSFW), Troll (FPSFW) and Giant (WFPSFW) - notice the pattern ?

Tutorial no.8
1. The most powerful spell around? That's Finger of Death (PWPFSSSD). 
2. ...It can't be countered, but it can be mirrored (cw)

Tutorial no.9
1. Playing with friends can be a lot more fun. Send them an invite. 
2. You can also set up a private game to play together.
3. Every time you win against a powerful warlocks your score will go up to reflect your skill.

Tutorial no. 10
1. In melee games 3-6 players play at the same time
2. Common spells are Fire and Ice Elementals (cWSSW, cSWWS) and Storms (SWWc, WSSc)
3. Resistance will protect you (WWFP, SSFP)
4. Checkout the full rules at (https://games.ravenblack.net/rules)

**Comment by Pz1c** [comment]
maybe in future we should create battle scenario for newbie
scripted interaction with bot

**Comment by Prulon** [comment]
yep, probably in the future we should also let players only start with a few spells, and then get more spells as they make progress
