### ISSUE TITLE
[CRITICAL BUG] Cannot play against a bot

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#228]
I update to the new version and crated a new game against a bot.
The problem is that I cannot enter the game. I can click on the new game but nothing happens. 
Tried killing the app and getting back in but it doesn't work.

**Comment by Pz1c** [comment]
check it

**Comment by Pz1c** [comment]
I saw problem with forced surrendering in waiting game try to fix

**Comment by Pz1c** [comment]
bot try finish stacked battle and attack server with this command and receive 500 server error
are you got such error?

**Comment by Pz1c** [comment]
found and fix problem 
build new release 
1.9.8.4
