### ISSUE TITLE
Make charm monster nicer

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#23]
1. When casting a charm monster, right after picking the target monster it would be good to direct the monster to its target. I added a screen to show that, with a message. See second row on the right
https://drive.google.com/file/d/1inB1WVvkmr8eyYqUAtIC0F8NwTxsVqU7/view?usp=sharing

2. This should also happen if your default spell is PSDD
3. You should only be able to pick a target for an opponent monster in a turn in which you have PSDx, and only if that hand is casting a spell at a monster. Otherwise picking opponent monster should be disabled (you can write something like "you can only direct enemy monsters if you charm them" or just disable it.

**Comment by Pz1c** [comment]
done
