### ISSUE TITLE
Bug - bot chat

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#230]
In games vs. a bot the chat icon should be hidden.
Also what the bot says should not show in the animation.

Otherwise it is very annoying especially if you play many games against bots

**Comment by Pz1c** [comment]
maybe show chat icon, but disable sending message?
or even allow send msg to bot and just hide bot messages from notification?

**Comment by Prulon** [comment]
I think it is just confusing.
There are anyways too many things for a new player to learn, so no need to
add chat as well.
Also it's strange to talk with a bot, and the training bot instructions are
confusing when comparing with the hints that we have at the beginning of
the game.

Why do you want to keep it?

**Comment by Pz1c** [comment]
right now it's showing because I forget to remove debug value)
and sometime chat icon appear in strange places, I hope that I fixed this problem but still a little bit afraid of this))

**Comment by Pz1c** [comment]
fixed
