### ISSUE TITLE
Notification for End of Game keeps showing

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#232]
I still keep getting the "Your Game is Over" notification, it never stops.

The logic should be that we only show a notification for end of game if the game finished AFTER the user was in the app for the last time (or last time he saw the game list screen) - is that possible?

**Comment by Pz1c** [comment]
I'll try to my best to fix this problem

**Comment by Pz1c** [comment]
hope that I found problem and fix it finally
