### ISSUE TITLE
Problem with spell selection

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#234]
Let's say that you have:
LH: PPWS
RH: xWWS

Right now the UI only lets you pick "counter spell" for your "RH" and this would cancel the invisibility.

What we need to do instead in such cases is to have "invisibility" as an option for both hands, and add the option of "Nothing" to LH.
So the options for LH would be: Invisibility, Nothing (and invisibility selected by default)
and the options for RH would be Invisibility, Counterspell (and invisibility selected by default)

(note: if you pick "Nothing" then skip the target selection screen)

We should do this for all 2 handed spells (except mirror where it is not needed)
PPws
DFWFd
DWFFd
WSSc
SWWc
DSFFFc
PWPWWc
cWSSW
cSWWS
cDPW
SPPc

**Comment by Pz1c** [comment]
small fix for your example
add none to LH only in case for RH exists spell that finish at this turn WWS in curr example
but in case we have not spell for RH 
list for LH will containt only Invisibility
