### ISSUE TITLE
Show open challenges

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#236]
Issue:
Right now it is hard to feel anything of the community, so the game feels like only standalone
We can do a quick fix to make it better

Task:
If the player is playing less than 5 games, so can still join a game, show in the game list also open battles.

Show only open battles that were:
- created by the app and are eligible for the player to join (elo range)
- or open battles that don't contain any word other than:: paracf, maladroit, no, bot, bots (case doesn't matter).

The game title should be:

- If very friendly: "Practice challenge by <Galbarad>"
- If friendly: "Open challenge by <Galbarad>"

The game should have a blue circle pimple, like active games

**Comment by Prulon** [comment]
Hey @Pz1c 
I saw you added this, which is great because now at last you can see there are other players too :)

Three comments:
1. Let's change the color of the circle in this case to #2DA0A5 so it doesn't feel overwhelming

2. Can we also put all the open challenges at the end of the games list, so for example if I have 2 games that I'm currently playing and 3 games that are open challenges then the challenges would show after the games that I'm already playing

3. I think that the words ParaFC Maladroit and NO BOT would be confusing to app players, can we just remove them from the text, also the text "created by android app..." looks strange when you are playing from within the app.

**Comment by Pz1c** [comment]
@Prulon please check color
![image](https://user-images.githubusercontent.com/5511791/209343073-895b8862-6721-4716-8a17-319d171af79c.png)

**Comment by Prulon** [comment]
I just updated the app and I don't see it...

**Comment by Prulon** [comment]
Also here's a dark circle icon that you can use:
https://drive.google.com/file/d/1AY0n6k8Ix8uKwvhiUXsoTS5Uy9ISYP0a/view?usp=share_link

**Comment by Prulon** [comment]
@Pz1c
