### ISSUE TITLE
Fix background color of intro section

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#237]
The background gradient should be between #210430 and #10C9F5

![image](https://user-images.githubusercontent.com/78275620/179369925-d02655ca-1312-4b4d-a5ce-3aaaef5908c3.png)

**Comment by Pz1c** [comment]
Hi @Prulon
looks like I'll have few hours per week of my own time)
lets try to do something)
please check 
![image](https://user-images.githubusercontent.com/5511791/208907617-f5e111e8-b766-4ca0-95d7-62f6db7c6f14.png)

**Comment by Pz1c** [comment]
fix bg under button 
![image](https://user-images.githubusercontent.com/5511791/208908707-b0d8815f-9455-41d1-8454-728fa97842d6.png)
