### ISSUE TITLE
New Intro Screen

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#238]
Issue:
Right now it takes players a long time till they start playing against other players. This may be one of the reasons that it takes them a while to fall in love with the game

Task:
After signup (not login) add one more screen (see below)
After clicking start do 2 things:

1. Create a warlock vs. warlock game
2. Create a game against a bot
Then immediately enter the game vs. the bot.

Additionally - 
Right now for new players the first screen says "Start Training" - let's change it to "New Game" so it's always the same

![image](https://user-images.githubusercontent.com/78275620/179370756-eb6c25ba-1b15-4e38-99e9-3440cd949d20.png)

**Comment by Pz1c** [comment]
@Prulon please check 
![image](https://user-images.githubusercontent.com/5511791/208922032-d61103ea-ab6c-455b-8838-e62cc3baa26e.png)

**Comment by Pz1c** [comment]
hm I suppose we need hide back button)

**Comment by Pz1c** [comment]
something like this
![image](https://user-images.githubusercontent.com/5511791/208922935-41841426-7fa0-49d5-8175-db2e1e9102e7.png)

**Comment by Pz1c** [comment]
looks like work
wait for design confirmation
