### ISSUE TITLE
[no fix] Good News - New 5 Star Rating in US 

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#241]
@Pz1c don't know if you saw - we got a new 5 star rating from US.
This brings us to 3.2 stars in general and 2.7 in the US (up from 3.1 and 2.6). 
If we get two more 5 stars from US then we get a 3.0 in US.

So far what works best is to send a game invite to new players, so they feel they have people to play with.
Right now there are:
marsh
Grimlord
Kronoturge

New players that started on the app, and play games when I invite them
Krono also sent an invite to another player, techmage, but seems like that didn't really mature to more than 1 game.

**Comment by Pz1c** [comment]
Great news!
Good to know that we have more player)
More player - more fun)

**Comment by Prulon** [comment]
Looks like suddenly a bunch of new polish players have joined even though they didn't play much. Don't know why.
