### ISSUE TITLE
Minimal Hall of Fame

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#243]
**Issue:**
right now players don't understand that there are more players in the game

**Solution:**
For a first step - let's add the lest screen - Hall of Fame. (Ignore the screens on the right, we will do them later)
The entry points for it should be: 1) from the main menu, add a section under "Spellbook" called "Hall of Fame" 2) When clicking on your own player's score icon, we have a modal with the score, wins, losses, etc'. Add a button to that screen saying "Hall of Fame"

![image](https://user-images.githubusercontent.com/78275620/196043769-bb70adca-ab6d-48c7-a025-e65f3022ffb3.png)

**Comment by Pz1c** [comment]
Partially done

**Comment by Pz1c** [comment]
will be done under #121
