### ISSUE TITLE
White bar at bottom of screen - when opening chat, and anther issue

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#247]
Just like https://github.com/Pz1c/WavingHands/issues/244 this issue now happens when opening chat.

Also, notice that the regular android menu is gone, it is covered by the full screen (e.g. 'back', 'home' buttons)

**Comment by Pz1c** [comment]
yep it's fullscreen now, it's only one way to fix this issue((
but Qt promisse fix this bug in next framework release
I'll check problem with chat

**Comment by Pz1c** [comment]
should be fixed in 6.4.2
https://codereview.qt-project.org/c/qt/qtbase/+/447965

**Comment by Pz1c** [comment]
in Qt versin 6.4.2 problem still exists

looks like problem appear when input field in bottom of screen and keyboard has no place to show

**Comment by Pz1c** [comment]
related with 
https://bugreports.qt.io/browse/QTBUG-109268

I'll move text input fields to the top as temporary solution

**Comment by Pz1c** [comment]
looks like solution will be permament because Qt framework 6.4.2 still contain bug and next update will be in few monthes
