### ISSUE TITLE
Updated Warlock stats

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#248]
Goal:
Help users discover the hall of fame, and invite other players for a game

Details:

Update the warlock stats based on the screen below (much like the new spellbook screen)
1. When looking at your own stats there should be only one button, and it should say "Hall of Fame" and take you to the hall of fame
2. When looking at another warlocks stats it should have the full details as below

Note that the icon is trophy_3D, which is a new icon see [here](https://drive.google.com/file/d/1jh0sSopxPoGcGSBbWpYO0Rra09D7yY2w/view?usp=share_link)

![image](https://user-images.githubusercontent.com/78275620/210149277-7c6f0f7c-5945-4ee6-b898-baa3a6a04731.png)

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/216773050-89931217-694e-4f62-9698-449d42e064ac.png)

**Comment by Prulon** [comment]
@Pz1c it would look a little nicer if you make the line longer, and give more space between the "score, played" column and the "won, lost" column (see image above)

Also I noticed that the time written in the "Last active" is often wrong.

**Comment by Prulon** [comment]
Just checked and "online indicator" isn't working.
I have a game against Ashai, and he was online 2 minutes ago, but the online marker doesn't show
