### ISSUE TITLE
Allow AI use new GUI

### ISSUE THREAD

**Issue by Pz1c** [Pz1c/WavingHands#25]
Bots shouldnt be able to change your target hand from left to right in an FFFFFF chain (just like it's impossible to do that on desktop

**Comment by Pz1c** [comment]
will be fixed when AI move to new version
it still on OLD cause I need fix AI for new controls

**Comment by Pz1c** [comment]
in progress

**Comment by Pz1c** [comment]
login, scan, accept challenge and create new bot challenge  - done
need another small bit - battle)

**Comment by Prulon** [comment]
@Pz1c does this mean that the bot will ALWAYS run? 
right now sometimes it does, and sometimes there's no bot available.
Will the bot run from the user's client side?

**Comment by Pz1c** [comment]
first time AI set choosed gestures on GUI)  
![image](https://user-images.githubusercontent.com/5511791/130085229-f6053bbd-c799-4e0f-a449-eb55830298ba.png)

**Comment by Prulon** [comment]
🌟💪🌟💪🌟

**Comment by Prulon** [comment]
Take a look at all the items in 1.9.1 - not sure if they overlap or not.
Also - can you share what's the change your doing for AI? is it going to run server side?

**Comment by Pz1c** [comment]
first of all I try to describe current problem of bots
bot use exact same app as ordinary player, so a large amount of login was related with old gui (for example bot always choose first spell in list after choosing gestures, but list sorted starting from largest usability of spell in concrete moment)
so after moving to new GUI bots can't use new buttons and lists and stay on old version of app (before you amassing design changes)
I separate moving on server side on few stages
1. move all AI login in one place (out from GUI) that's allow exclude gui for server version in future
2. new gui must show AI decision (chosen gestures and spells and targets for simplified debugging and AI development)
3. when bot will be work properly create new app without GUI 

for now I do 1 and 2 steps (cause I need visualization to check is AI decision correct)
as I say earlier I suppose do this two steps and running new BOTS version on my media server exactly as now bot running
after that fix all gui problem for players and start developing console version for "bot server"

**Comment by Prulon** [comment]
Got it, 
thanks for the detailed explanation

**Comment by Pz1c** [comment]
and now bot show paralyzed hand)
![image](https://user-images.githubusercontent.com/5511791/130238914-1e2d56a3-b9c9-4828-9faf-fe3f30abb4b9.png)

**Comment by Pz1c** [comment]
AI try to kill goblin with SD (side spell from Charm)
![image](https://user-images.githubusercontent.com/5511791/130244117-243b69e6-2001-40d1-88aa-0c6b89e460bd.png)

**Comment by Pz1c** [comment]
ok, looks like new AI at least not worse as old
https://games.ravenblack.net/warlocks?num=86235&full=1

**Comment by Prulon** [comment]
Great :)
Say, did you also fix the issue of bot shifting hands during paralysis?

**Comment by Pz1c** [comment]
yep it's fix paralyze 

interest fact: game has hidden variable with paralyzed hand that not store on server but read from client input
for example on turn 3 player cast FFF on turn 4 choose left hand and on turn 5 on page will be exists variable with LH value) but if you remove this variable you can choose hand 
loos like Raven do some hotfix and leave as is

today I run new bot on my workstation to check if all fine

so we can test new bots AI and push some hotfixes)

**Comment by Pz1c** [comment]
hm looks like I forget about force surrender functionality for bots

**Comment by Pz1c** [comment]
add force surrender

**Comment by Prulon** [comment]
Great :) so when can I try it live?

**Comment by Pz1c** [comment]
as I see new bot properly work almost 24 hours
so you can try new bot logic right now)
and to bad news
my old-old-phone too old for new bot app(
but I try to fine some way to fix this or just take not so old phone)

**Comment by Pz1c** [comment]
hm some problem with app on phone
perhaps problem related with special build that installed on phone from APK instead of Google Store

**Comment by Pz1c** [comment]
yep reinstall not help, I'll try create normal release in Play Market

**Comment by Prulon** [comment]
Cool :)

**Comment by Pz1c** [comment]
and we online now)
problem was related with std::sort on Android
write own sorting and voila)
