### ISSUE TITLE
small Typo

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#250]
In the text "Cast magic missile on Prioli" it should be "Cast magic missile at Prioli" with "at" instead of "on"

**Comment by Pz1c** [comment]
are you mean text in history?
or in bubbles before battle turn?
this text generated by site
https://games.ravenblack.net/warlocks?num=87843

**Comment by Pz1c** [comment]
hm I am sorry, but where you found this text?)
can't find it(

**Comment by Prulon** [comment]
when you select a target for a spell

**Comment by Pz1c** [comment]
fixed
