### ISSUE TITLE
1.9.9.8 A lot of things not working any more

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#251]
1. I no longer see the blue dot indicating if there's a new turn
2. The names of the games stay as "waiting"
3. Not seeing new game recommendations any more
4. There's still a white bar when you try to chat that obscures the text line so it's very difficult to write and to see what you write
5. The notes for what happened in the turn sometimes behave in a strange way so when I click to see the next note sometimes what happens is that it clicks on something behind the text like the chat or history
6. You sometimes get error screens. For example - I won a game (forced turn), the game still shows as waiting, then I click it and get an error screen
7. Also I think that the "Online" indicator is not working anymore, haven't seen it for a very long time
@Pz1c

**Comment by Pz1c** [comment]
sorry for delay, have a lot of work last few weeks
I'll try to fix problems 
and I can't find verion 1.9.9 that should fix problem with white bottom bar

**Comment by Pz1c** [comment]
please check 1.9.9.9

**Comment by Prulon** [comment]
1,2,3 seem ok.
I'll pay attention to the others.

A few more comments:
1. when clicking "Practice together" from the Hall of Fame the wrong game is created. I expect a new private very friendly challenge with that player, instead there's a new Friendly challenge that is public open to all. Didn't check about the "Challenge" option
2. New issue - even though I have a registered player the app doesn't let me open a new game when I have 3 games
3. Find warlock by name: Fix the text to "Start a practice game with Galbarad?" when you do find the warlock's name. If you can't find the warlock change the text to "Hmm, can't find anyone called Galbar"

@Pz1c

**Comment by Prulon** [comment]
one more typo - 
in the error screen "Something is wrong..." when you cannot create a new game fix the "whicj" text to "which"

**Comment by Prulon** [comment]
Online indicator doesn't work.
I have a game against Ashai and he was online 2 minutes ago, but the online marker doesn't show on our game

**Comment by Pz1c** [comment]
Hi Prulon, looks like I'll have a few days for working on game)
I'll try to fix ll cricical problems

**Comment by Pz1c** [comment]
looks like this problem both should be fixed with #254
