### ISSUE TITLE
View old games

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#252]
Goal:
Let player, especially new players look back at games to see what happened and learn. See also recent comment on feedback form.

Tasks:
1. From game end let users go back to see the game
2. From "waiting" screen let users go to see the game
3. Create a new view for a game when done / waiting
See images below

In the end game screen:
1. remove the game history and only keep the last turn's messages (see image)
2. Add 2 CTAs: a) View - to see the game itself b) Rematch - to create a new game against the same player. Friendly or Very Friendly the same as this game.

In the game view there are a few changes:
1. no next turn actions
2. change the CTA to "back"
3. can't change targets for monsters

![image](https://user-images.githubusercontent.com/78275620/216790497-decc9fcd-ac93-4527-adfc-dd808739f5bc.png)
![image](https://user-images.githubusercontent.com/78275620/216790650-13f8b4ab-da73-44d8-97d3-ff535137f2e2.png)

![image](https://user-images.githubusercontent.com/78275620/216790562-0c550f5c-b256-4912-a500-52bd23662a06.png)

**Comment by Pz1c** [comment]
@Prulon looks like we haven't enough space to place additional buttons
![image](https://github.com/Pz1c/WavingHands/assets/5511791/4f18a498-2a01-4781-a861-20241dd2de5f)

**Comment by Prulon** [comment]
@Pz1c see in my example above - 
the end game screen should not have all the history, only the last turn's chat. So there is enough space

**Comment by Pz1c** [comment]
@Prulon please check
![image](https://github.com/Pz1c/WavingHands/assets/5511791/f69e0e8d-c8c3-4f06-ae00-b1494f41f028)

**Comment by Prulon** [comment]
nice

**Comment by Pz1c** [comment]
first step - done
now app had new parsing for finished games and store final json for usage 
need to do - small changes for battle window 
some read only mode)
![image](https://github.com/Pz1c/WavingHands/assets/5511791/f7d45f67-a7ff-40b6-94bc-3ea9058f5126)

**Comment by Pz1c** [comment]
yep all should be fine 
Pz1C cross fingers on his left hand

**Comment by Pz1c** [comment]
release 2.1.0 on review
