### ISSUE TITLE
Improve experience of spell selection

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#253]
**Why:**
Help new users get in the game, and feel that it is more visual

**Task:**
1. Add spell icons in size 48x48 to the gesture screen, see image below 
2. Note: background color should be:
- For all enchantments and monsters x551470
- For healing spells: x0654C0
- For damaging spells (inc. FoD etc') xFEE2D6
-3 Add the icons also to the next screen, and also to the spellbook

![image](https://user-images.githubusercontent.com/78275620/218277341-0566c8f3-bac4-44a4-a4a8-641339c5c527.png)

**Comment by Pz1c** [comment]
really cool idea
but I can't found few icons for spells, time stop and finger of death for example

**Comment by Prulon** [comment]
FoD: 
https://drive.google.com/file/d/1v78-3nvX4-8Sq0jSYxvxFiT_kby-6iVm/view?usp=sharing

time stop:
https://drive.google.com/file/d/1XJ9-a2p_HO_yPJxWS-G2sCpkp5hM2i3A/view?usp=sharing

You actually have icons for all the spells - when you click on a spell in the spellbook you have the icon showing

@Pz1c

**Comment by Prulon** [comment]
Really happy to see this @Pz1c but there is a problem with the background colors.
They are OK in the main spellbook, but messed up in the gesture selection 

![Uploading Screenshot_20230518-082510.jpg…]()

**Comment by Pz1c** [comment]
should be fixed in 2.0.0
