### ISSUE TITLE
Touch doesn't always go to the right screen

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#256]
Issue:
Right now sometimes when I get the list of actions that happened in the last turn, and I click them, the click is preformed on another screen.
Example: I click on the news, and then what opens is the status of an old game. It seems like the app thinks that my click is on the "Game List" screen and not on the battle screen. Sometimes I get the "chat" to open instead.
Note: this happens when clicking in the actual text. If I click the '>' arrow or the 'got it' then it is ok

Task:
Clicks on the turn news text should always advance the text and not go to other screen elements or other screens

**Comment by Pz1c** [comment]
should be fixed in 1.9.10
