### ISSUE TITLE
Fun new turn news

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#257]
The following might be a simpler way to implement the animations, keeping them static
Why:
Current news update is hard to understand and not fun

Tasks:
1. Stretch the news area over the whole width, covering all of the bottom area
2. Add a 128x128 box including a 96x96 icon, and sometimes also another 64x64 smaller icon, see images below
3. The 128x128 box should have a 2 pixel external line colored as follows:
Damaging spell:- outline: x210430, fill: xFEE2D6
Enchantment or monster, or someone hit:- outline: : xFEE2D6, fill: x210430
Cure: outline: x210430, fill: x0654C0
4. Rules:
When a spell is cast - show its icon
When a user is hit by a spell - show the heart icon, with updated lives following the hit (in bold)
When a monster is hit by a user or a spell - show the icon of the monster
When a user or monster is hit by a monster - same, but also add a smaller 64x64 icon of the monster (see image)
When a user says something put the cha icon
When in poison/disease show the number of remaining turns in bold, and the small icon of the spell (see image)

![image](https://user-images.githubusercontent.com/78275620/219500455-c4f6b32e-184f-4190-ad03-df0ba7ce1e6a.png)
![image](https://user-images.githubusercontent.com/78275620/219500510-f949ab1c-7f3f-41ce-a9ef-dd06dc72775d.png)
![image](https://user-images.githubusercontent.com/78275620/219500549-11dd533b-7d80-4407-a6f5-a42ac4e9e81a.png)
![image](https://user-images.githubusercontent.com/78275620/219500573-58a3340f-4bd5-45d5-9d41-45c637ac6274.png)
![image](https://user-images.githubusercontent.com/78275620/219500627-6a99f46f-4d39-4e11-8f85-7190407a2a55.png)
![image](https://user-images.githubusercontent.com/78275620/219500652-2abc3ccd-01aa-43ad-a136-ddbc8da6e42e.png)
![image](https://user-images.githubusercontent.com/78275620/219500671-ac28fb46-fe5f-4b99-9a65-b6b659971472.png)
![image](https://user-images.githubusercontent.com/78275620/219500689-a7075ef9-83d1-4e31-8f44-eb0043882621.png)
![image](https://user-images.githubusercontent.com/78275620/219500718-69b3da26-1138-414d-80e1-541c9eeb722c.png)
![image](https://user-images.githubusercontent.com/78275620/219501029-4805faf0-849a-4d46-8b96-8d8422551101.png)

**Comment by Pz1c** [comment]
![image](https://github.com/Pz1c/WavingHands/assets/5511791/66666490-c25b-4223-9882-3a7f0bb1e8ab)

**Comment by Pz1c** [comment]
work in progress

**Comment by Prulon** [comment]
Nice :)

**Comment by Pz1c** [comment]
Galbarad starts to lose coordination.
Smelly Goblin is hit by a Magic Missile, for 1 damage.

**Comment by Pz1c** [comment]
sorry it's was message just to collect all standard game messages

**Comment by Prulon** [comment]
![image](https://github.com/Pz1c/WavingHands/assets/78275620/9aa3224c-ed1a-4f43-9b36-55aea9faf0ed)

**Comment by Pz1c** [comment]
oh too late I saw this((


fix this in 2.0.1

**Comment by Pz1c** [comment]
fix appear in 2.0.1
