### ISSUE TITLE
Bug in melee, free roaming monsters not seen

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#259]
**How to reproduce:**
Play a melee battle with 3 players: A, B, C
Player A summons a goblin
On the next turn player B kills player A
On the next turn player C wants to cast charm monster at the goblin, but C cannot do that because you don't see the goblin

**Task:**
When you kill a player in a melee that player should still show, with their monsters
and you should be able to target those monsters.

**See for example here:**
https://games.ravenblack.net/warlocks?num=87998&turn=37
BioLogin is dead, but he has a goblin that is still alive

**Comment by Pz1c** [comment]
should be fixed
