### ISSUE TITLE
Bug in Samsung A32 - see app review

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#260]
"Somewhat confusing interface, made more difficult by the fact that for some reason the bottom of the window is cut off on my phone (Samsung A32). Once I understood the flow - choose spell, select target, confirm - I'm having a good time with it."

**Comment by Pz1c** [comment]
I'll try to jump on 6.5 looks like bug fixed there 
[QTBUG-109268](https://bugreports.qt.io/browse/QTBUG-109268)

**Comment by Pz1c** [comment]
stuck on building Openssl 3 binaries for android

**Comment by Pz1c** [comment]
should be fine after release
