### ISSUE TITLE
additional information about monsters

### ISSUE THREAD

**Issue by Pz1c** [Pz1c/WavingHands#262]
"After protection (WWP) is cast on a monster there is no way to see how many turns protection there is still left on that monster."

@Prulon pleasse check this issue
I suppose we need change hp to "!" sign for monster under some effects shield, paralyze or somehing else

**Comment by Prulon** [comment]
Let's add icon 32x32 in the bottom left corner, see 2 images below, If there is more than 1 enchantment then show only the first one.

and also add an "enchantments" section, but only if there is an active enchantment.
This enchantment section should also show for warlocks, so if you click on a warlock that is under an enchantment then the enchantment will show there

![image](https://user-images.githubusercontent.com/78275620/223838791-69ad6767-63e8-4416-a22d-4468e96d1cbf.png)

![image](https://user-images.githubusercontent.com/78275620/223840150-4e98d0a2-a500-4026-b950-c421ecc1e575.png)

**Comment by Pz1c** [comment]
done
