### ISSUE TITLE
Bug when charming opponent to do '>'

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#265]
When charming an opponent and selecting '>' as their action then for the following turns you see blank gesstures.
Actually because it's not important to have opponent do '>' (because it doesn't make them stab on RB) then it's best to just remove this option

**Task:**
When charming opponent the '>' gesture should be disabled (grey) so you cannot select it for your opponent

**Comment by Pz1c** [comment]
but in case you know that opponent try to cast spell on own changing gesture to stab may be useful)

**Comment by Pz1c** [comment]
hm, looks like problem not in charming but in stab

**Comment by Pz1c** [comment]
fixed
![image](https://github.com/Pz1c/WavingHands/assets/5511791/e1c25bd6-fd41-4a5b-a613-08e32c4cf9d9)
