### ISSUE TITLE
Add "Toasts" possibility into Game

### ISSUE THREAD

**Issue by Pz1c** [Pz1c/WavingHands#268]
#266 it's best to add a toast saying "Click to make your spell permanent"

@Prulon please add other places where toasts will be useful

**Comment by Pz1c** [comment]
notifications already precented 
QWarloksDuelCore::showNotification

**Comment by Pz1c** [comment]
![image](https://github.com/Pz1c/WavingHands/assets/5511791/19dc55b4-bbdc-408d-b39c-a71e7ebcae49)

**Comment by Prulon** [comment]
@Pz1c English fix:

"To make Blindness permanent, click the permanency icon and then choose a target."

**Comment by Pz1c** [comment]
done
