### ISSUE TITLE
2 bugs in Hall of fame

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#269]
1. Clicking hall of fame from main menu doesn't work
2. If you get to hall of fame from score, then click on a player and click practice together it doesnt work. A new game is created but the player is not invited

**Comment by Pz1c** [comment]
1 done

**Comment by Pz1c** [comment]
2 - changed site behavior (( 
I suppose site owner do nothing with this
I'll add some crutch in code

**Comment by Prulon** [comment]
Adding a two bugs - click on 'all times' in hall of fame then click on one of the old warlocks. It says last active 3 days ago, even on Taliesin

And second bug - the 'Online' badge doesn't show anymore. It's not working

**Comment by Pz1c** [comment]
`bounds=(1,120,300,600,1800,3600,7200,21600,43200,86400,130000,172800,259200,500000,1000000,20000000);

That's in seconds, and goes 00ff00, 11ee00, etc.`

**Comment by Pz1c** [comment]
![image](https://github.com/Pz1c/WavingHands/assets/5511791/6584dcd6-3446-469b-987c-9071f336f280)

**Comment by Pz1c** [comment]
online should be fixed too

**Comment by Pz1c** [comment]
![image](https://github.com/Pz1c/WavingHands/assets/5511791/fbe8c47f-8816-4fd2-942a-ad8e421bab33)

**Comment by Pz1c** [comment]
"If you get to hall of fame from score, then click on a player and click practice together it doesnt work. A new game is created but the player is not invited"
should be fixed too
