### ISSUE TITLE
review orders screen improvement 

### ISSUE THREAD

**Issue by Pz1c** [Pz1c/WavingHands#27]
In the review screen - clicking on a line should go to the relevant screen. For example, clicking on "Left Hand: ..." should go to edit the left hand action. clicking on a monster should go to edit the target of the monster.

**Comment by Prulon** [comment]
I've added a "review screen" to the design
(see the top right 3 screens here: https://drive.google.com/file/d/1inB1WVvkmr8eyYqUAtIC0F8NwTxsVqU7/view?usp=sharing)

**Comment by Pz1c** [comment]
partially done
hands and monsters
todo: charming, delay, permanent...
