### ISSUE TITLE
Reddit promotion

### ISSUE THREAD

**Issue by Pz1c** [Pz1c/WavingHands#270]
@Prulon may I ask you create some text for game promotion on Reddit?
my last attempt was not very successful 
https://www.reddit.com/r/playmygame/comments/l6rr02/spellcaster_turn_based_warlocks_duel_waving_hands/

**Comment by Prulon** [comment]
Hey, 

I have a special story, one which you probably don't come across everyday, and I need your help.

It started with a game that Richard Bartle, the great inventor of MUDs created back in 1977. The game called Spellbinder (see [Wikipedia](https://en.wikipedia.org/wiki/Spellbinder_(paper-and-pencil_game)), and [boardgamegeek](https://boardgamegeek.com/boardgame/5818/waving-hands)) had lots of players about 20 years ago, but less than 10 active players remain. 

So 2 of us took the challenge to create an android app for it, as a free, no ads, open source project, and we're hoping to revive and build a community for this amazing game.

Can you help review the app? Any feedback is welcome.
Also any ideas on how we can build a community would be great.

Here's a [link ](https://play.google.com/store/apps/details?id=net.is.games.WarlocksDuel&hl=en_US&gl=us) to the Android app, which we recently re-wrote from scratch.

![image](https://github.com/Pz1c/WavingHands/assets/78275620/cce3b73b-8fc1-4a0e-a1ad-98a7705f4224)

**Comment by Prulon** [comment]
@Pz1c here's an extended version:


Hey gamers!

I have an extraordinary tale to share with you today, and I need your help.

It all started with Spellbinder a game that Richard Bartle, the great inventor of MUDs created back in 1977. This game used to have lots of players about 20 years ago, but less than 10 active players remain, keeping this legend alive.
(see [Wikipedia](https://en.wikipedia.org/wiki/Spellbinder_(paper-and-pencil_game)), and Waving Hands on [boardgamegeek](https://boardgamegeek.com/boardgame/5818/waving-hands))

So, two of us took on the mission to revive this amazing old game through an open-source Android app! The app is called Warlock's Duel, and it takes the concept of rock-paper-scissors and amplifies it with magical spells. Picture this: in a standard game of rock-paper-scissors, a set of two consecutive turns with rock followed by scissors would mean a magic missile, and a set of paper-paper-rock would mean summoning a goblin.

That's exactly what happens in Warlock's Duel, but with a lot more depth. You have six gestures (and a dagger) that you simultaneously play with both hands, allowing you to create a total of 45 unique spells.

Can you help by reviewing the app? It is a free, no ads. Any feedback is welcome.
Also any ideas on how we can build a community of PvP players would be great.

Here's a [link ](https://play.google.com/store/apps/details?id=net.is.games.WarlocksDuel&hl=en_US&gl=us)to the Android app, which we recently re-wrote from scratch.

**Comment by Pz1c** [comment]
Great
Thanks
I'll post after 2.1.1 version will be released (fixed all know bugs)

**Comment by Prulon** [comment]
I think that it would also be good to do a screen recording of what a game looks like (a short video)

**Comment by Prulon** [comment]
Here's a quick one I made. Not perfect at all, but something to start with

https://github.com/Pz1c/WavingHands/assets/78275620/e7e63996-8b5a-463c-8151-86a8bfb9e1d3

**Comment by Pz1c** [comment]
draft for reddit post
will be published after 2.2.0 appear in store
https://www.reddit.com/user/Galbarad/draft/1fd67d4a-0b92-11ee-8048-c6f6bd5ae167

**Comment by Pz1c** [comment]
https://www.reddit.com/r/playmygame/comments/14a92ls/spellcaster_turn_based_warlocks_duel_waving_hands/?sort=new

**Comment by Pz1c** [comment]
I ask my friends to like post (crossed fingers)
But I haven't lot of friends and especially with reddit account)

**Comment by Prulon** [comment]
@Pz1c if you can still edit the post, move the image much higher so it shows on the feed even if you don't go inside

**Comment by Prulon** [comment]
@Pz1c added this:
https://www.reddit.com/r/opensourcegames/comments/14ab56y/warlocks_duel_an_open_source_revival_of_a_famous/
