### ISSUE TITLE
New turn news - list of fixes

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#271]
Huge progress on the new turn news! :)
I played with it, and here are some fixes that I think we need to do:
1. UI fixes from #257 and adding another image below with the height sizes. Also see in the image below that I added the player's name above the heart. It is in font size 16 and in bold
2. The arrows should be bigger, if you did size 21 try 28 or 42
3. After poison I got a '16' instead of "4" on the turn when I cast DFPW to remove it (see [image](https://drive.google.com/file/d/1BljnQoucB2NiNAJqNC4xDkRUPxnEW3cn/view?usp=sharing))
4. When someone dies like [here ](https://drive.google.com/file/d/1BnwnAARqPLvKyjW76NjdgGTsFoxIAsUe/view?usp=sharing) add the icon of [RIP ](https://drive.google.com/file/d/1dXpzGC6Q123Hmd9f8r_YTj1pcLvE2WJq/view?usp=drive_link)
5. When you write "- 1" when someone is hit, make that font bold
6. I think we should remove all the less important comments like [this one] (https://drive.google.com/file/d/1BkXv_xd9j3QgOrq3m3zGzmektNQOWjeV/view?usp=sharing) and [this one](https://drive.google.com/file/d/1BiZ_-BUS7x-d_oUlwzI2KK6FXmpLEcai/view?usp=sharing) because right now they are confusing. The way to make them not confusing is to put them immediately after the spell, but I believe this is tough to implement, and might not provide that much value

![image](https://github.com/Pz1c/WavingHands/assets/78275620/71a6f5a7-cfb3-44f8-ae6b-1ff01b4f1ec1)

**Comment by Pz1c** [comment]
all done except 6 
I suppose we should take all this messages and provide right icons for that 
for example for first message need to show counter spell shield icon + small icon of Cause Heavy Wounds
(it's should help with #227 )
@Prulon ?

**Comment by Pz1c** [comment]
to do
![image](https://github.com/Pz1c/WavingHands/assets/5511791/7b05b36d-186a-40ec-accb-46c05d1b9cdb)

fixed
![image](https://github.com/Pz1c/WavingHands/assets/5511791/e7fbdc9d-efe5-413a-bbb9-5576836f1870)

**Comment by Prulon** [comment]
Few more comments: @Pz1c 
1. you should use the small_heart.png icon, not the heart.png
2. the corners of the box should be more round

About your question from above and the solution with the icons - it works only if the message is located right after the spell (as I wrote in 6) otherwise it is very confusing, and we better just remove it

**Comment by Pz1c** [comment]
![image](https://github.com/Pz1c/WavingHands/assets/5511791/f703bb01-a94d-4381-95e3-282d010f5da3)

**Comment by Prulon** [comment]
Also I think that when the target is a warlock, and no life is lost then it might be better to use the spellbook icon (the hat) instead of the heart

**Comment by Pz1c** [comment]
we can't move it because of spell order
"The next table lists the spells in the order that they would take effect if they were all cast in the same round."

![image](https://github.com/Pz1c/WavingHands/assets/5511791/dfc650c8-ee5d-4fd6-9a9d-d1ab30097fd3)

https://games.ravenblack.net/rules/1/quickref.html

**Comment by Pz1c** [comment]
@Prulon 
![image](https://github.com/Pz1c/WavingHands/assets/5511791/b1d28fff-699f-4a21-8e3f-a85825db373d)

**Comment by Prulon** [comment]
I know the spell order, but it is possible to take the list and sort it in a different way. Though I guess it is not easy.

For example if you have prulon casts cause light wounds at Galbatad
and then galbarad casts shield and then 
wounds appear on Galbarads body 

You can change the order so that 3 would show after 1.

**Comment by Pz1c** [comment]
yes, you are right not easy((
but in most cases will be just few actions during turn and it's should be easy to understand

**Comment by Pz1c** [comment]
i push to release version with all fixed and with "nice strange messages" hope you like it (and maybe it will be more clear to understanding)

**Comment by Prulon** [comment]
Great :)
