### ISSUE TITLE
2 fixes for the new version

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#272]
1. in the gesture screen the words "Summon Fire Elemental" and "Summon Ice Elemental" get overlapped because there's not enough space. Let's remove the word "Summon"

2. In the hall of fame, if you click practice together - right now it creates a friendly game but it should create a "very friendly" game. Also it's very hard to click it because it is very close the the "Challenge" button, so we need to add 6 more pixels between them

**Comment by Prulon** [comment]
2 more:
1. The number of hours in the Hall of Fame is often not correct. For example, I now look at Dubber that was active 3 minutes ago and in the Hall of Fame it shows 15 hours.

2. I had 2 cases were the app got stuck, and I was not able to go into my game at all. I had to go to RB to do my turn

**Comment by Prulon** [comment]
and one more :) the "Online" tag should also be there when the game is in "waiting" stage

**Comment by Pz1c** [comment]
"I had 2 cases were the app got stuck, and I was not able to go into my game at all. I had to go to RB to do my turn"
moved to #273
