### ISSUE TITLE
app stuck in battle

### ISSUE THREAD

**Issue by Pz1c** [Pz1c/WavingHands#273]
I had 2 cases were the app got stuck, and I was not able to go into my game at all. I had to go to RB to do my turn

**Comment by Pz1c** [comment]
@Prulon please give an example what game and what turn?
maybe you do some specific? summon elemental or some rare spell?

**Comment by Prulon** [comment]
This one was stuck since the middle of the game (don't remember which turn) until the end:
https://games.ravenblack.net/warlocks?num=88313&full=1

**Comment by Pz1c** [comment]
nothing found (( 
I'll try to reproduce problem with my test account tomorrow

**Comment by Pz1c** [comment]
@Prulon may I ask you to show hidden gestures
![image](https://github.com/Pz1c/WavingHands/assets/5511791/4a249d74-85e5-4b4b-a4bd-8f06f790a76e)

**Comment by Pz1c** [comment]
try to reproduce)
https://games.ravenblack.net/warlocks?num=88347

**Comment by Prulon** [comment]
@Pz1c 
I think itcwas after casting PSDF at myself on turn 33

**Comment by Pz1c** [comment]
nope, I check Charm Person works fine
@Prulon please provide hidden gestures for your battle with Kasia
I already reproduce 14 steps)

**Comment by Pz1c** [comment]
hm suppose it was fff and -sf

**Comment by Prulon** [comment]
Yes

**Comment by Pz1c** [comment]
problem on turn 22
https://games.ravenblack.net/warlocks?num=88313&turn=22
because of chat message with not escaped special symbols
Oh, on discord channels of some youtubers and on reddit (S\Patient Gamers)

**Comment by Prulon** [comment]
Nice catch!

**Comment by Pz1c** [comment]
fixed 
![image](https://github.com/Pz1c/WavingHands/assets/5511791/5bb6db1d-044d-44bd-bb76-7f230f2144d9)
