### ISSUE TITLE
small caps issue

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#277]
**Issue**:
This is most simple to explain by example.
Say I 'c' with both hands.
Now on the next turn I want to go for CW / CD.
So I click 'w', but the app forces me to go for a 'cw' mirror and do a W with both hands.
In fact in the spell selection screen you have Mirror and then another Mirror.
This is confusing to players (see https://games.ravenblack.net/warlocks?num=88353&turn=9, where Ashai ended up moving from the app to RB to play the turn).

**Task**
In the spell selection add a "none" option
If you chose that option then only 1 hand will get the gesture.
So in the above example: 
I have 'C/C' 
I click 'W'
I pick "None" as spell
Result 'CW / C'

**Comment by Pz1c** [comment]
@Prulon please clarify, should I add "none" option for all cases?

**Comment by Prulon** [comment]
@Pz1c yes. And if you pick the 'none' then the gesture does not get duplicated to the other hand

**Comment by Pz1c** [comment]
should be fixed in 2.1.2
