### ISSUE TITLE
View old turn - small fixes

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#281]
Great seeing the old turn info @Pz1c !

2 small fixes:
1. when entering the old turn - the fonts of the turn news are in some weird not normal color
2. Need to hide the gesture buttons, for for you and for opponent. Because you cannot really play a new turn

**Comment by Pz1c** [comment]
1. done
2. I can't see any turn new for old turn may sorry I ask for some screenshot I do not get this problem(

**Comment by Prulon** [comment]
See image 
![Uploading Screenshot_20230610-010027.jpg…]()

**Comment by Prulon** [comment]
![Screenshot_20230610-010027](https://github.com/Pz1c/WavingHands/assets/78275620/0abdae59-b896-421e-80dc-5d5e59d1084f)

**Comment by Pz1c** [comment]
this should be fixed in 2.1.1 
I just got mail that this release already on live 
please check is problem fixed with new version

**Comment by Prulon** [comment]
It looks fixed for old games, but not for viewing games that are still on in "waiting" after submitting orders

**Comment by Pz1c** [comment]
oh i got it
thanks for details

**Comment by Pz1c** [comment]
both problems should be fixed in 2.1.2
