### ISSUE TITLE
animation small fix

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#282]
Issue:
The gestures do not always light up correctly during the new turn info.
For example - 
play against a bot and play DSF/SFW.
on the third turn you get "Summon Goblin" message but all the gestures are ON.

click next, now you have "Maladroitness" which works fine, and only opponent DSF is ON. BTW if possible, it would be best to hide all the gestures except the ones of the actual spell (i.e. the DSF), just like when you select a target for a spell we hide everthing.

click next now you have a second "Maladroitness" which is also OK, but the heart background colors are wrong -it's better when the order is "cast" not to light any heart at all.

click next now you have a "Summon Goblin" but opponent gestures are also on when they shouldn't.

click next now all gestures are ON but they should all be OFF (because there's no "Cast" in this step)

click next - same all gestures should be OFF

**Comment by Pz1c** [comment]
should be fixed in 2.1.1
