### ISSUE TITLE
Hall of Fame - last active time is not correct

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#283]
I often click on HoF to check the last time that a player was active, but it is often not correct.
For example I've just seen on the main list that Ashai is online (because he just played) and then on the HoF it showed 1 day ago.

Additionally, it would be great to have the "online" symbol also on the HoF

**Comment by Pz1c** [comment]
looks like I found root of the problem (crossed fingers)
should be fixed in 2.1.4
![image](https://github.com/Pz1c/WavingHands/assets/5511791/1a286d84-c43a-4723-a9fe-d258fe63a424)
