### ISSUE TITLE
Bug after completign a game

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#286]
I opened a new player (Test992)
Created a new game against a bot and surrendered.

The game ended but it keeps showing on the list of games to play, with a green circle showing there's a turn to play

**Comment by Pz1c** [comment]
will be fixed in 2.1.1

**Comment by Pz1c** [comment]
ups closed wrong issue)

about topic
I can't reproduce problem @Prulon may I ask you to check one more time perhaps it was some issue with ravenblack site

**Comment by Prulon** [comment]
Still not working.
The game vs Icraeverra is complete (surrendered) but still shows

**Comment by Prulon** [comment]
![Uploading Screenshot_20230610-010739.jpg…]()

**Comment by Prulon** [comment]
![Screenshot_20230610-010739](https://github.com/Pz1c/WavingHands/assets/78275620/0e9907bc-016a-41fe-b1c1-ec31f60b4948)

**Comment by Pz1c** [comment]
I suppose Refresh didn't help?
are you try open this game?

**Comment by Prulon** [comment]
Refresh didn't help.
What did help was that after I clicked on my other game, and then clicked Leave then all games got refreshed correctly

**Comment by Pz1c** [comment]
oh it's my fault I should take in mind your words about new user (((
fixed in 2.1.3
