### ISSUE TITLE
Improve tutorial

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#288]
Now that we have the new full screen instructions we can improve the onboarding tutorial by adding images.

Let's add the following images
  
 **Letter 'S' icon** --> fillDictionary("hint_1_1", "", "", "Hint: Start by picking the 'S' gesture with both hands");
    **goblin icon** -->  fillDictionary("hint_1_2", "", "", "Then in the next 2 turns cast Summon Gobline ('SFW')...");
    **magic missile icon** -->  fillDictionary("hint_1_3", "", "", "...and Magic Missile ('SD')");
    **surrender icon** -->   fillDictionary("hint_1_4", "", "", "Be careful, P/P with both hands means surrender.");
     **spellbook icon** -->  fillDictionary("hint_1_5", "", "", "Check your spellbook to learn more spells. Let's start!");

**Comment by Pz1c** [comment]
@Prulon we have a small problem)
we need bg color for icon 
![image](https://github.com/Pz1c/WavingHands/assets/5511791/95247623-bd48-431f-87c4-988908b7a3cb)

**Comment by Prulon** [comment]
#10C9F5
@Pz1c

**Comment by Pz1c** [comment]
![image](https://github.com/Pz1c/WavingHands/assets/5511791/feadcf64-6ae0-450d-83e8-cc92abe6a488)

@Prulon  great, looks amassing!
I'm always a little jealous of people who have a sense of style
