### ISSUE TITLE
Clarification of gesture submission (add word 'Go')

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#294]
Following some feedback on clarity of UX in gesture submission:
**Add the word 'Go' next to the submit, font 28, color #A8F4F4**

See image below:
![image](https://github.com/Pz1c/WavingHands/assets/78275620/c61f0bc3-c6f9-4f97-be0f-34ab05b7f993)

**Comment by Pz1c** [comment]
will be in 2.1.2
![image](https://github.com/Pz1c/WavingHands/assets/5511791/59552bfd-c02c-436f-949d-0147eea747e5)
