### ISSUE TITLE
2.1.2 fixes

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#296]
Happy to see 2.1.2 out @Pz1c

Few fixes:
1. the word "Go" should show only when the button is enabled, meaning only after you click a gesture.
2. The "None" option of selecting a spell - looks like I didn't understand your question. I meant that None shows in 2 cases: a) like before when there are absolutely no spells to cast b) when the spell ends with a lower caps, for example 'cw' so if I pick 'w' and I don't want double 'w' then I can pick None. In other cases like if you just click 'P' then there should be shield but no 'none'
3.  creating a new player and finishing a game against a bot I still have that game show as pending, and it doesn't disappear

**Comment by Pz1c** [comment]
1. done
2. done
3. found

**Comment by Pz1c** [comment]
3. will be fixed in 2.1.3 push release today
