### ISSUE TITLE
Tutorial - don't show '?' icons

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#297]
Right now the tutorial shows '?' icons after the first game.
That's not a good experience.

We can either remove them or put other icons instead:

 **Amnesia icon -->** fillDictionary("hint_2_1", "", "", "Hint: Disruptions like DPP (Amnesia) and SWD (Fear) disrupt your enemy...");
**X icon -->**    fillDictionary("hint_2_2", "", "", "...but when two are cast at the same time they cancel out.");
**Goblin icon -->**    fillDictionary("hint_3_1", "", "", "Hint: When you summon a goblin (SFW), cast it at yourself, so it serves you.");
**Goblin icon -->**    fillDictionary("hint_3_2", "", "", "Afterwards, click the goblin to set its target.");
   
**Counter spell icon -->**    fillDictionary("hint_4_1", "", "", "Hint: There are two ways to counter a spell (WPP, WWS).");
**Small Heart icon -->**    fillDictionary("hint_4_2", "", "", "Cast it at yourself to prevent spells and monsters from hitting you.");
**no icon -->**    fillDictionary("hint_4_3", "", "", "Cast at an opponent to prevent them from summoning a monster.");
**stars icon -->**    fillDictionary("hint_5_1", "", "", "You're doing great! Keep up.");
**no icon -->**    fillDictionary("hint_5_2", "", "", "Playing against other players and friends is fun...");
**no icon -->**    fillDictionary("hint_5_3", "", "", "Games with other players are played in turns.");
**no icon -->**    fillDictionary("hint_5_4", "", "", "You can play up-to 3 games at the same time, and you have up to 3 days to play each turn.");

**Comment by Pz1c** [comment]
will be fixed in 2.1.4
also I move all icons to qwarlockdictionary.cpp so you can easily change it
