### ISSUE TITLE
version fixes (wait reproducing)

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#303]
1. In the Hall of Fame often the list of players is not up to date, and the last active time is wrong, and the 'online' marker is not updated.
2. In the Hall of Fame if you click 'Practice together' it should be a Very Friendly challenge, but right now it's a Friendly one.
3. The submit button in the Review Orders screen sometimes doesn't work and I need to restart the app
4. it would also be great to add animation to that submit button like you do for the other ones.

**Comment by Pz1c** [comment]
3. I suppose some error appear under hood may I ask for example of problem orders?

**Comment by Prulon** [comment]
I will try to recreate

**Comment by Pz1c** [comment]
2 I suppose that it was missclick because action for this button is right
so I try to give more space between those two buttons 
4 done

**Comment by Pz1c** [comment]
1. should be fixed

**Comment by Pz1c** [comment]
in case 3. problem reappeared please create new issue
