### ISSUE TITLE
Fix following Reddit comment (resize battle window)

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#305]
From Reddit comments:
"tried it on my oneplus nord and the screen cuts the content so I can't read what's happening in the tutorial. also is always nice to put a password confirm or a view password field to make sure you are actually inputing the right password while registering"

**Task**
1. Let's check the screen cut issue
2. About password screen: add a hide/don't hide icon like the image below. Default is hide. Icon size is 48x48
Added these icons here:
https://drive.google.com/file/d/1ngJI-cJKDDjV9glyqJu1u34qGAHc94EN/view?usp=sharing
https://drive.google.com/file/d/1SUZNtBT-B0yDJSD5OhTHZoiVn9oLkNBD/view?usp=sharing

![image](https://github.com/Pz1c/WavingHands/assets/78275620/2089a609-fcbd-4aa6-bd2e-dddafb9b309b)

**Comment by Pz1c** [comment]
1. may we ask for screenshot?
2. great I'll do this in 3-4 days because I'll be a little busy in few next days

**Comment by Pz1c** [comment]
1. or at least confirmation about screen size for this phone 1080x2400 (FHD+)

**Comment by Prulon** [comment]
He wrote that it is oneplus nord, so I think you are right on 2400x1080

**Comment by Prulon** [comment]
@Pz1c see screenshot provided on reddit

**Comment by Pz1c** [comment]
hm looks like we need little bit change anchoring (crossed fingers)
![image](https://github.com/Pz1c/WavingHands/assets/5511791/362a1038-53fe-4309-a8f6-98841eaef059)

**Comment by Pz1c** [comment]
or problem related with black top rectangle((

**Comment by Pz1c** [comment]
https://www.reddit.com/r/opensourcegames/comments/14ab56y/warlocks_duel_an_open_source_revival_of_a_famous/

**Comment by Pz1c** [comment]
I'll try to find someone with such phone to test but right now I should move this bug to later milestone

**Comment by Pz1c** [comment]
maybe problem gone after app move to Qt 6.6 I asked vikkio to confirm on reddit
