### ISSUE TITLE
Some things got messed up in new version

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#309]
1. The word go always shows on gesture, even before selecting one
2. If you choose 'P' you have none as a spell, but you should not
3. In target selection everything shows (remember we cleaned up before? So now it is not clean again) and the animation on the heart does not show

**Comment by Pz1c** [comment]
looks like I clean up some changes(( I'll check

**Comment by Pz1c** [comment]
should be fixed in 2.2.2
