### ISSUE TITLE
UI Fixes for game list screen and battles screen

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#31]
See list of fixes and pixel measurements here: 
https://drive.google.com/file/d/1IMkC9ScWZ4UZcA3R1BP3tIWpnTzSpn2E/view?usp=sharing

Mainly in game list: 
Fix top header and icon sizes and location
Fix location, size, corners, gradient of main button
Fix List items, paddings, sizes
Fix text size and fonts

in battle screen:
Fix all paddings, sizes of cards and other items
Fix size of heart
Fix gradients of cards

**Comment by Pz1c** [comment]
yep, I have problem with UI (
thanks for size in px I'll try apply it to GUI

**Comment by Pz1c** [comment]
work in progress) of course scrollbar become invisible on mobile
![image](https://user-images.githubusercontent.com/5511791/120649321-4a3ae400-c485-11eb-9bba-917e811a8a85.png)

**Comment by Pz1c** [comment]
P.S. already fix icon for win battle

**Comment by Pz1c** [comment]
hope finish battle screen tomorrow

**Comment by Prulon** [comment]
btw - let's change the icon of the spellbook (top right) from the trophy, to the wizard's hat (as was before).
The icon of the trophy was there in the old screen, and I forgot to change.

**Comment by Pz1c** [comment]
icon change - done, 
battle screen - loading ...

**Comment by Pz1c** [comment]
@Prulon small question about battle screen 
about gestures list 
I see that some dark and some light and as I see light gestures is a part of possible spell, but how I can choose what spell should be lightened? 
maybe show longest sequence as active spell, or change color of gestures after player choose gesture and spell

**Comment by Prulon** [comment]
@Pz1c 
The letters that should be highlighted are the ones that can be continued to a spell.
For example, if I have 'DPS' then 'D' should be dark and 'PS' should be light, because PS can continue to PSDF or PSDD or PSFW, but there's no spell that starts with DPS

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/120813491-97d35180-c556-11eb-9e31-6689d386924f.png)

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/120813673-c81af000-c556-11eb-9ff9-41aa5a4ea7ed.png)

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/120814290-6909ab00-c557-11eb-9d19-2e9f74a5978b.png)

**Comment by Pz1c** [comment]
first version of battle screen
hope problem with screen position related with Windows Title Bar 
I'll try to fix this

**Comment by Pz1c** [comment]
ok looks fixed for Windows and should be fixed for Android
![image](https://user-images.githubusercontent.com/5511791/120817087-1087dd00-c55a-11eb-8fad-cda2492e694f.png)

**Comment by Prulon** [comment]
nice, great progress!

- notice that the corners of the cards are too much rounded, and the corners of the monsters and spells are too little rounded
- Also notice the letter icon sizes should be smaller (64px for regular letters, 84px for the selected letters)

**Comment by Pz1c** [comment]
@Prulon  please check new corners and height for letter 
![image](https://user-images.githubusercontent.com/5511791/121010186-c55e0c00-c79d-11eb-810a-6e5487dc0687.png)

**Comment by Pz1c** [comment]
last version
![image](https://user-images.githubusercontent.com/5511791/121010556-3e5d6380-c79e-11eb-959f-a499b237469e.png)

**Comment by Prulon** [comment]
Looks great :)

Notice that the heart icon is too big, you should use the "small heart" icon

**Comment by Pz1c** [comment]
always forget about small heart)
but not today)
![image](https://user-images.githubusercontent.com/5511791/121021291-e9bfe580-c7a9-11eb-8eaa-6914b33ceeaa.png)
