### ISSUE TITLE
Make texts a shorter and bigger in the new turn news

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#311]
**Small improvements to turn news that can make it a lot more easy to read**

Change texts and increase fonts as follows:
When the text is "X attacks Y" ==> change to only "X attacks" (when the target is still alive the animation above will help see the target)
When the text is "X is hit by a ..." ==> change to only "X is hit"
When the text is "X's left hand is paralyzed" ==> change to "X is paralyzed"
When the text is "X starts to lose coordination" ==> change to "X loses coordination"

**Comment by Pz1c** [comment]
should be fixed in next release
