### ISSUE TITLE
API level requirement from Google

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#314]
We've detected that your app is targeting an old version of Android. To provide users with a safe and secure experience, Google Play requires all apps to meet target API level requirements.

From August 31, 2023, if your target API level is not within 1 year of the latest Android release, you won't be able to update your app.

To continue making updates to your app, ensure your app targets Android 13 (API level 33).

**Comment by Pz1c** [comment]
should be fixed in 2.3.0
