### ISSUE TITLE
Rejected game - bad experience

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#316]
**Issue:**
Right now when you invite another player and they reject the invite you can't see that they rejected.

**Task:**

1. Change the message to "<Galbarad> has rejected your invite"
2. CTA "Got it!" --> goes back to the full game list + Delete the game

**Comment by Pz1c** [comment]
it's because we haven't any events for this
but you right we can track player's invite and change status in case invite vanished from waiting list

**Comment by Prulon** [comment]
@Pz1c I think there's a better way.

In RB when you go to that game you see something like
"Galabarad rejected your invite" - so it means this is something we can get from RB.

So we can change the message on our side too

**Comment by Pz1c** [comment]
Hm sorry not noticed
 ok I'll try this

**Comment by Pz1c** [comment]
should be fixed in 2.3.0
