### ISSUE TITLE
Small updates to New Game screen

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#319]
Issue:
Private duels seem to be the main thing players do, and it's a bit hard to know how to do practice games.

Task:
Change the names of buttons and order as follows:
1. For practice: Instead of "Other options", put a "Practice Duel" which would open the private very friendly game selection directly instead of going through the current modal
2. Change "Play" to "Public"
3. Put "Private" as the second CTA for duels, which will open the warlock selection screen
4. Put "Invite a Friend" as the third CTA

See image below

![image](https://github.com/Pz1c/WavingHands/assets/78275620/63769c9d-625b-4100-8ca1-fd3b46f3dfd1)

**Comment by Pz1c** [comment]
@Prulon  for now "More options" allow start with bot, open very friendly game and find by nae warlock for vf game
perhaps we need instead of "more options" add two buttons practice duel and invite a friend?

**Comment by Prulon** [comment]
No, keep it simple. Only the practice duel (=private very friendly). We
have invites in other places

**Comment by Pz1c** [comment]
should appear in 2.3.1
