### ISSUE TITLE
Error messages suck :)

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#321]
**Issue**: 
Right now there are lots of error messages for network etc'

**Task**
what can we do?

**Comment by Pz1c** [comment]
in case network error we should check games.ravenblack.net perhaps site is down because too much requests or something else 
looks like we get new big task create out own server and move mobile players there (of course manage mixed game on current site)

**Comment by Prulon** [comment]
@Pz1c 
I don't think that's needed yet.
The issue is that you get an error message and then if you click refresh it's ok.

I think we need two things:
1. Add a "re-try" automatically after 1 second or so
2. Change the error messages so they would show as a toast and not a popup saying something like "Your internet has gone invisible, try again later"

**Comment by Pz1c** [comment]
Re try already did but maybe need more delay before try. I suppose now retry doing immediately

**Comment by Pz1c** [comment]
should be fixed in 2.4.0
