### ISSUE TITLE
Discussion of priorities

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#323]
Let's keep this as a live thread to discuss priorities of milestones.

Status: Right now we have more active players than ever, even though still small, and players play against each other.
That's a good sign, and I think many of the social features we added helped this like match suggestions, and HoF.
Also more players complete onboarding, though many get stuck either on turn 1 or turn 3 (when they get the first real spell results).

I think that the focus should be:
1. Fixing stuff that makes it hard to play against other players, Goal: keep the players we got so far to keep playing.
2. Fix other experience issues, and improve the new turn news to make it less overwhelming, and help new players get in
3. Online games? we now have many times where more than 1 player is online, so this could be a strong addition to keep players live
4. Lower priority fixes - minor broken things, for better overall experience
5. Visual animations - to make the whole experience more interactive and fresh and feel more 'casual game', to attract new players
6. Social - message other players and view other players, to keep strengthening the social aspects which are one of the key reasons people stay

Makes sense?

**Comment by Pz1c** [comment]
of course, maybe I never said this but you have a great vision of way to evolution this game, so I should just shut up and do))
and look like I'll get more time to development maybe not each day but

**Comment by Pz1c** [comment]
what you think about unlocking high level spell in case player got fight with human (maybe check is opponent mobile player and unlock only for web player)??

**Comment by Pz1c** [comment]
also maybe we need some "news feed" for example add notice about invite or reject player's invite, chat message etc..

**Comment by Prulon** [comment]
About first question - why do you think it's needed? (and do you think it's a high priority)
second question - it's a nice idea, let me think about it. For now we have the notification saying that the game started, and nothing about rejected

**Comment by Pz1c** [comment]
first question: I suppose it little bit confused when you got spell on you that you haven't in your spellbook but I agree that is not hight priority
second: great happy you like it

also have new proposal, maybe we should rise community?
I see some old player back to game maybe we can use fb page for this?
https://www.facebook.com/WarlocksDuel/

**Comment by Pz1c** [comment]
in case you interest you can join fb page and I'll give you admin access

**Comment by Prulon** [comment]
About rising community - I think it's a good idea, but we need to plan well.
What's the strategy? what will get them back? when is the right timing? how do we keep them around? how do we approach them.

I don't know if the FB has many old followers or not. It could be one of the channels.
I'll add a special issue for this
