### ISSUE TITLE
Small fix for deleting games

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#326]
**Issue**
When you open a 2 player game, and then cancel the invite the current status is a zombie game.
You have a message saying "multi player game for 2 players" with options to "keep waiting" but there's no one to wait for.

**Task**
If you have a 2 player Private game, and there are no other players invited then automatically delete the game

**Comment by Pz1c** [comment]
@Prulon maybe also do auto forced turn?

**Comment by Prulon** [comment]
What do you mean?
After how much time?

**Comment by Pz1c** [comment]
maybe +1 day?

**Comment by Prulon** [comment]
I think we can do after 7-10 days, not less...
I'm ok with 7 days

**Comment by Pz1c** [comment]
should be fixed in next release
