### ISSUE TITLE
User feedback: Fix input text boxes font size

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#327]
Quoting from user feedback form:
 _The font size in all text entry boxes is not correctly scaled, resulting in letters which are much larger than the space they should occupy. While not a functional issue, this does diminish the polish of the app and may rub new users the wrong way_ 

I think that this would relate to 2 places:
1. in registration the user name and password
2. in chat

**Comment by Pz1c** [comment]
should be fixed in 3.2.1
