### ISSUE TITLE
Fixes for last version

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#328]
1. The "Online" word in the game list now overlaps the name and is impossible to read

2. The main menu has top and bottom white areas
![Screenshot_20230919-224949](https://github.com/Pz1c/WavingHands/assets/78275620/a936d5ea-3ccf-48de-832d-1da4a381a080)
![Screenshot_20230919-072746](https://github.com/Pz1c/WavingHands/assets/78275620/2569a578-3cba-46e4-82f8-07b689c43d86)

**Comment by Pz1c** [comment]
should be fixed in 2.3.1
