### ISSUE TITLE
Make spell descriptions easier to read

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#33]
Change the format of spell descriptions to be like this:

**"Spell Name"**
"1 line description" - see below

**Details:**
"Full description"

For example:
**Charm Person**
choose opponent's next gesture, on one of the hands

**Details:**
Except for cancellation with other enchantments, this spell only affects Warlocks. The subject of the spell submits orders as normal, but the caster of the spell also submits a gesture for one of the subject's hands. The subject uses the gesture submitted by the caster for the next turn. If the subject is only so because of a reflection from a Magic Mirror the subject of the mirror assumes the role of caster and decides his opponent's gesture. If the subject is also the subject of any of Paralysis, Amnesia, Confusion, another Charm Person, Charm Monster, or Fear, none of the spells work.

Take the one line descriptions from this list:
P - Shield (Defend against monsters and stabs)
WWP - Protection (Defend against monsters and stabs for 3 turns)

SD - magic missile (Do 1 damage)
WFP, WPFD - Cause wounds (Do 2 damage, Do 3 damage)
DFW, DFPW - Cure (Heal 1 or 2 damage)

SFW, PSFW - Summon goblin (Monster with 1 hp, usually cast at yourself) or Ogre (Monster with 2 hp, usually cast at yourself).

DPP amnesia (Opponent repeats last turn gestures)
DSF maladroit (Opponent must do same gesture with both hands)
SWD fear (Opponent must do P or W or '>' or '-')
FFF paralysis (Choose opponent's hand. Its next turn will be based on last turn as follows: [F or C] --> C. [W or P] --> P. (S or D) --> D)
PSDF charm person (Choose opponent's next gesture, on one of the hands)
PSDD charm monster (Take control of a monster. Cast it at the monster, and choose a new target for that monster to attack)

WPP, WWS - Counter spell (Cast it at the target of the spell that you wish to counter, not at the caster. It also acts as shield against attacks)

**Comment by Pz1c** [comment]
added
you can change almost any text in game in /cpp/qwarlockdictionary.cpp
short descriptions start on line 169
