### ISSUE TITLE
[Critical issue] Notifications not working

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#334]
**Issue**
1. Since the last version I stopped getting notifications. Not getting any time of notification. I also checked my app permissions and it seems like notifications are allowed
2. I also noticed the new "Notification" line in the menu - when I click on it and then I click "Enable Notifications" nothing happens, I expect it to open the notification settings but it does not.
3. Also the "Notification" should be above the "Sign out"
4. Change the name from "Notification" to "Notifications"

**Comment by Prulon** [comment]
Looks like notifications are still not working

**Comment by Pz1c** [comment]
yep(( sorry little busy(( i'll fix this asap

**Comment by Pz1c** [comment]
notification work already loooks like we can push current test into production
