### ISSUE TITLE
Some text fixes

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#335]
The last changes in new turn texts are great. 
We need a few more:

1. Killing - When a monster dies like "Small goblin dies" - use the larger fonts. Now very small.
2. Charm - Change "Apo11o looks intrigued by Prulon" to just "...At Apo11lo" - and use bigger fonts
3. Charm - Change "Apo11lo is charmed into making the wrong gestures with his right hand" to "Apo11o is charmed" and bigger fonts
4. Cure - make the fonts of "Prulon is healed" bigger
5. Paralysis - Change "Prulon's hands start to stiffen" to "Prulon is paralyzed" and increase font
6. Double enchantment - change "Prulong shakes his head and regains control as enchantment cancel each other out" to just "Enchantments cancel each other" and bigger fonts
7. Cause wounds - Change "Wounds appear all over 1Pi's body!" to ""1Pi is wounded" and bigger fonts
8. Counter spell - Change "Eru is covered by a magical glowing shield" to "Eru has a magical shield" and bigger fonts
9. Protection - Change to "Eru is protected" and bigger fonts
10. Shield - Change to "Eru has a shield" and bigger fonts
11. Magic mirror - Change to "Eru has a reflective shield"
12. Fire storm - Change "A Fire Storm rages through the circle!" to "A Fire Store rages!" and bigger fonts, and put the icon of the storm
13. Fire storm damage - Change "Prulon is burnt in the raging Fire Storm for 5 damage" to "Prulon is burnt" and bigger fonts
14. Disease - increase fonts of "Prulon is a bit nauseous"
15. Surrender - change the icon of "Prulon stops his heart though the force of will alone" to the R.I.P icon

**Comment by Pz1c** [comment]
1-11 done
12-15 in progress

**Comment by Pz1c** [comment]
@Prulon  sorry don't get 15 point should I replace heart with RIP icon on battlefield??
![image](https://github.com/Pz1c/WavingHands/assets/5511791/dba06ab0-5dd0-4bdd-89e3-9bc511bc1f97)

**Comment by Prulon** [comment]
Looks good
