### ISSUE TITLE
permanency bug

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#337]
**Issue**:
Permanency does work on two handed spells like PPws, probably because in RB you need to sumbit it as 2 handed

**Comment by Pz1c** [comment]
![image](https://github.com/Pz1c/WavingHands/assets/5511791/b020ccd7-96be-4235-82a9-db42f1e6fb89)
looks like you try finish two handed spell on the left hand
I'll try to fix this

**Comment by Pz1c** [comment]
should be fixed in 2.3.11
