### ISSUE TITLE
[Critical bug] Games with bots often don't start right away

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#339]
**Issue**
When creating a new training game, you sometimes need to refresh a few times until the bot joins the game.
When you click new game you only see that the game is waiting to start.
You can see new players starting multiple new games and not playing

**Comment by Prulon** [comment]
I think we just need a loader until it starts

**Comment by Prulon** [comment]
Looks like new players are abandoning the game before a first play because of this

**Comment by Pz1c** [comment]
should be fixed in 2.3.10
