### ISSUE TITLE
Created new Welcome flow

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#34]
New flow: see [here](https://drive.google.com/file/d/1C_cgSuZaOlR65tzNb5KCL8dxSTxtQeq0/view?usp=sharing)

**In this flow you will see:**

1. 3 welcome screens
2. Signup / Login screens

**Notes:**
- I think that the most important thing is to create a good looking signup screen. Even before welcome screens. We need to start getting people to signup and use the app.
- To create each of the screens I've added a background image (jpg), and a title image (png) see links below.
- All screens where created as 1920(h) x 1080(w)
- All other texts are using our usual color pallet: #E7FFFF for the titles, #A8F4F4 for the submit and login/signup actions, #544653 for the placeholder texts for wizard name, #FEE2D6 for the input wizard name, and for the next/back actions.
- Icons for submit and for next/back are taken from regular icons we use in the app
- When putting an email I think it is important to set the ravenblack settings: email hidden, and no email notifications for new turns or for anything. Otherwise users will go to desktop when receiving email

**Backgrounds and titles -** 
see 4 JPG files named Step 1/2/3/4 for backgrounds and 5 png files for titles named Step 1/2/3/4 signup/4 login 

**Full directory**: [here](https://drive.google.com/drive/folders/1Ly_NpSFC33CQ4EZxLJMoccaNZEK2SsRs?usp=sharing)

FYI @Pz1c

**Comment by Prulon** [comment]
I had an idea - 
As a quick way to push this in, you can do the following:
1. Create the signup/login as above

2. Take the welcome screens and add them to the Google Play images
here are JPG images for google play:

https://drive.google.com/file/d/1Us2IUjvk6XLwbNQA3ekmVRNgTgTKM1R-/view?usp=sharing
https://drive.google.com/file/d/1iGeIwDTExWFBvFOUr8Y3Ap5piG0XyiHn/view?usp=sharing
https://drive.google.com/file/d/1LGZph4gNcsWYhHUt-xvNDbbhRqgBbQaH/view?usp=sharing

**Comment by Pz1c** [comment]
uh I found your email)

**Comment by Pz1c** [comment]
one small problem, according  to UK lows we should show checkbox that confirm at least 13 years for users
perhaps we can change rating to 13+ in app store, but as for me better both check box and in app store

**Comment by Pz1c** [comment]
also I can generate random password that will be sent on email by games.ravenblack.net (maybe need some alert about this)

**Comment by Prulon** [comment]
@Pz1c please see updated screen for the signup [here](https://drive.google.com/file/d/1C_cgSuZaOlR65tzNb5KCL8dxSTxtQeq0/view?usp=sharing)

About removing password - doesn't sound right, because then if a user tries to login again then experience would be bad, 
and I don't think anyone would abandon because of having to add a password

**Comment by Prulon** [comment]
@Pz1c 
Please see here phone PNGs for the welcome flow

https://drive.google.com/file/d/1ch1xWRccuiKQ6o6Qtv8bHqTKfBSKS0E5/view?usp=sharing
https://drive.google.com/file/d/1JvyVZAFPX8JnYjGQKVOZ3cpVtonurOSi/view?usp=sharing
https://drive.google.com/file/d/1KqIxP7DinPmuwYBQCXdutHazEsvZkI9-/view?usp=sharing
https://drive.google.com/file/d/1cxDYQh1ZEAPXNf6qBIfNRVpjV5RvAKl-/view?usp=sharing

Also - I've fixed the first screen in the flow 
https://drive.google.com/file/d/1C_cgSuZaOlR65tzNb5KCL8dxSTxtQeq0/view?usp=sharing

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/118263173-97e3b280-b4be-11eb-95fb-2e3f84836e1f.png)

first step
still need to change white bg for edits
add submit
and coloring

**Comment by Prulon** [comment]
Say, why doesn't it cover the full page height?

**Comment by Prulon** [comment]
also there's no need for "back" and "next" on this screen

**Comment by Pz1c** [comment]
> Say, why doesn't it cover the full page height?

I have no idea(
but I'll try few tricks to fix this

**Comment by Pz1c** [comment]
small step for human and also small step for out project
![image](https://user-images.githubusercontent.com/5511791/118513035-fb2e4880-b73b-11eb-802e-d74afdcbc780.png)

**Comment by Pz1c** [comment]
I'll try to add checkbox for age

**Comment by Pz1c** [comment]
> Say, why doesn't it cover the full page height?

root cause is "header" element of main window (menu bar on top)
I replace special item header with simple rectangle and all work fine

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/118659111-b4048e00-b7f5-11eb-8a88-b3445f23a841.png)
new look)

**Comment by Pz1c** [comment]
ups, forget about back button

**Comment by Pz1c** [comment]
back button fix + 
![image](https://user-images.githubusercontent.com/5511791/118661805-22e2e680-b7f8-11eb-8970-471dca06dca1.png)

**Comment by Prulon** [comment]
@Pz1c you have a typo:
should be "Sign Up" and not "Sing Up"

**Comment by Pz1c** [comment]
uh looks finished)
"forgot password" some time in future)
