### ISSUE TITLE
Notification bug

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#340]
**Issue:**
I keep getting this strange notification.
It seems to replicate mostly when:
1. I have low / no internet connection
2. I kill the app and open it

![Screenshot_20231225-231558](https://github.com/Pz1c/WavingHands/assets/78275620/60debfad-f9e1-4059-954d-bae53a9926ad)

**Comment by Pz1c** [comment]
may I ask you to "open" this notification little more to check error details
I pretty sure that it's "system" notification perhaps related with background check game site to get updates

**Comment by Prulon** [comment]
I cannot, but:
1. It always happens when low/no internet, and opening the app. 
2. I believe it is a sys notification, saying that the app just failed in what it was trying to do

**Comment by Pz1c** [comment]
ok thanks 
I'll try to reproduce this and fix

**Comment by Pz1c** [comment]
will be fixed in 2.3.10
