### ISSUE TITLE
Bug, scrolling of spell descriptions and others does not work

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#342]
**Issue**
If you go to a spell with a long description, or to a game history, or to a chat and try to scroll then you can just scroll a bit, but not all the way. This issue seems to happen across the app. (also if you have many open games you cannot scroll in the game list, etc')

**Comment by Pz1c** [comment]
found problem with scroll on main screen but can't reproduce any problem in other places neither on samsung s9 no s10
perhaps fix on main screen will fix other problem but it's low chance

**Comment by Prulon** [comment]
work now

**Comment by Prulon** [comment]
works now
