### ISSUE TITLE
Screen is cut at bottom

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#343]
Just got a Samsung S24 Ultra, 
I see the battle screen cut at the bottom, so for example part of the new turn news text is cut, and part of the icons

**Comment by Pz1c** [comment]
great that we have a phone where we got this problem and can test 
I hope that I'll be able to fix few issues per this weekend

**Comment by Pz1c** [comment]
please check is it black panel on top of the screen (look like app slip down)
(try to understand where is problem)

**Comment by Pz1c** [comment]
@Prulon perhaps game do not recognize right screen resolution when you got time please check firebase analytic to check screen resolution send by game. 
I check game with 410 * 888 screen resolution on my PC (same scale 2.16 as for 3120*1440) but it's looks normal so I suppose that problem in detection right resolution

**Comment by Prulon** [comment]
How do I check?

**Comment by Pz1c** [comment]
hm got same problem on my S10 
looks like root cause is front camera I'll try to fix this
