### ISSUE TITLE
[Critical] Refresh doesn't refresh

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#344]
**Issue**:
Often when I click refresh it doesn't refresh the game list. 
For example, I have just played a turn in a game, but it still shows with the green circle and says ready to play, even though it is waiting for the other player to play.
Maybe it doesn't have enough time to get response from RB server?

**Comment by Pz1c** [comment]
@Prulon  please check in 2.3.10

**Comment by Prulon** [comment]
@Pz1c  I have 2.3.9 which seems like the latest version, how do I get 2.3.10?

**Comment by Pz1c** [comment]
oh sorry I hope you read this after weekend and 2.3.10 will be exists at that moment 
I hope I publish this version tomorrow with pack of fixes

**Comment by Pz1c** [comment]
@Prulon may I ask you to check now?
