### ISSUE TITLE
Game list - show only one challenge per player

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#349]
**Issue:**
Right now there are 5 open challenges by succat. This looks bad for new players that just get a huge list of games from the same player.

**task**
Only show the first challenge from each player

**Comment by Pz1c** [comment]
should be fixed in 2.3.11

**Comment by Prulon** [comment]
I still get multiple open challenges from Succat

**Comment by Pz1c** [comment]
uh yeh I add description to unique check 
but you right it should be excluded 

will be fixed in next version

**Comment by Prulon** [comment]
Cool, btw - pay attention to the thread on Bio's Reddit, mentioning you
[here](https://www.reddit.com/r/Spellweavers/comments/1ain2xb/comment/kxz3ufe/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

@Pz1c
