### ISSUE TITLE
Update app market content

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#35]
@Pz1c 
This topic is about improving the text on Google Play, to get more users into the app.
---------------------------------------------
**Background research**
I looked up a keywords, to see what the app ranks for and what could be more options.
It seems that right now most prominent keyword is "Warlock" where the app shows at no. 8, 
and also "Warlock games" where the app is no. 16.
It is actually quite hard to find more keywords that the game ranks for.

Additional possibly relevant keywords (using autocomplete) are:
2 player games
2 player offline games
2 player offline games with friends
2 player strategy games
2 player strategy games offline
2 player turn based games
2 player turn based games offline
2 player turn based
2 player brain games
2 player brain games offline
turn based strategy
turn based
turn based games
turn based games offline
turn based games with friends
strategy turn based games
strategy games offline
strategy turn
strategy brain games
brain games offline
brain games 2 player
battle of minds
warlock spells
warlock games
spell
2 player duel games
duel 
duel games
duel games 2 players
duel games 2 players offline
bluffing game
geek games
pvp offline games
pvp games
turn based pvp games
etc' 

----------------------------------------------------------------------
**Based on this, I suggest to make the following changes:**

1. **Change the app name to: Warlocks Duel game (Beta)**     --> remove the words "Waving hand" from the title, I don't think there's any search volume there, and it's distracting, and add the word game. I the future we may experiment with "Warlocks duel - Turn based game" or something like that 

2. **Change the description of the game to the below:**
-----------------------------------------------------------------------

**Warlocks Duel is a free turn based strategy game for 2 players. (PvP game)** 

Players duel in a **battle of minds**, casting spells at each other, and sometimes bluffing ("Shadow casting"). 
Warlocks **spells** are text words, where each word like 'DPP' (Amnesia) is a spell, and each letter is a hand gesture ('D' for digit). 

Warlocks duel is also known as **Waving hands** and **Spellbinder** - the strategy game that was published by Richard Bartle (1977) about a battle between two wizards (see Wikipedia reference below) 

**Few words of caution**
- This is a relatively **slow and relaxed** offline game. Sometimes warlocks play a turn or a few turns per day. 
- For faster games you can **train against a bot**, or play up to three 2 player games at the same time.
- This is an **open source** project, in beta - UI work is still in progress and keeps getting improved.

**Features**
- **Training bot**
- **2 player games** (PvP), played offline in turns. Up to 3 games at at the same time.
- **45 spells** for summoning monsters, enchanting players and monsters, countering, poisoning and many more
- **100% Free**, no ads, no in-app purchases
- **Forum**, tips and strategy discussions: https://slarty.proboards.com/
- **Beginners tutorial**: https://slarty.proboards.com/thread/944/tutorial-newbies

**References**
- Board game geek - https://boardgamegeek.com/boardgame/5818/waving-hands
- Complete rules, on board game geek - https://boardgamegeek.com/filepage/99152/waving-hands-modernized
- Wikipedia - https://en.wikipedia.org/wiki/Spellbinder_(game)

Thanks

Pictures provided: Manuele la Puca

**Comment by Pz1c** [comment]
App name - Warlocks Duel game
Full description - changed - Play market allow not much for text format, but I was try my best)
need few day for review(

**Comment by Prulon** [comment]
Looks good except that there are some extra line breaks at the beginning.
I would remove 1 empty line between the first line and the second line
and remove 1 empty line between the second line and the third line.

Other than that all's good.

**Comment by Pz1c** [comment]
done
