### ISSUE TITLE
more text fixes

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#350]
Few more text fixes and things that were not fixed following https://github.com/Pz1c/WavingHands/issues/335

Counter spell - Change "Eru is covered by a magical glowing shield" to "Eru has a magical shield" and bigger fonts
Countered a spell - Change "Eru's shield blurs for a moment" to "... is countered" and bigger fonts
Protection - Change 'Dubber protected" to "Dubber is protected"
Blocked a magic missile - Change "A magic missile bounces off Eru's shield" to "Eru blocks Magic Missile" 
Elemental blocked - change "Dubber's shield keeps the Fire Elemental at bay" to "Dubber blocks Fire Elemental"
Elemental hits - change "Dubber is burnt for 3 damage" to "Dubber is burnt" and increase fonts
Killing a warlock - increase fonts of "Eru dies." now they are too small.
Invisible - remove "Galbarad begins to shimmer" 
Invisible - change "There's a fash, and Galbarad disappears" to "Galbarad is invisible" and increase fonts
Attack invisible - change "Bearded Goblin swings wildly for Galbarad, but misses" to "Bearded Goblin misses Galbarad"
Amnesia - change "Galbarad forgets what he's doing, and makes the same gestures as last round!" to "Galbarad is forgetful!"

**Comment by Pz1c** [comment]
should be fixed in 2.3.11
