### ISSUE TITLE
Fix click on spellbook in gesture selection

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#36]
When in gesture selection, we have for example:
PSDF              Charm Person

**Existing behavior:**
Click selects the next gesture

**Desired behavior:**
Click on the spell name "Charm Person" opens the description of the spell
Click else where on the line (i.e. on PSDF) selects the next gesture (as today)

**Comment by Pz1c** [comment]
hope complete

**Comment by Prulon** [comment]
Doesn't work for me

**Comment by Prulon** [comment]
Let's just do it this way, I think it would anyways be better:
If you didn't pick a gesture yet, then any click on a spell will show the spell description, and NOT change your gesture.

So for example, let's say that I already have 'PSD'
1. Now I click on 'PSDF    charm person' --> I should see the description
2. Then I click on 'F' --> F is selected, 'Default Spell' is selected
3. Now I click on 'PSDF    charm person' --> Charm person spell is selected
4. Now I click on 'F' again --> F is unselected, and no spell is selected, and I see the regular spell book
5. Now I click on 'PSDF    charm person' --> I should see the description (like in line #1)

**Comment by Pz1c** [comment]
hope fixed
