### ISSUE TITLE
Major fixes

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#37]
1. **Fix end turn**
When waiting for other player to play, right now it shows the full game history. Instead I think it is better to only show the last part, meaning only show:
"Your orders are in for this turn.
LH: W
RH: W"
and not show all the part above this.

2. **Fix targeting nobody/default**
Cast at Noboday / Default target - I saw that you changed title from 'All' to 'Nobody', but this doesn't look like the right solution to me. Please see alternative solution on row 3, two right most screens here: https://drive.google.com/file/d/1inB1WVvkmr8eyYqUAtIC0F8NwTxsVqU7/view?usp=sharing
I basically added 2 icons, one for selecting a "nobody" target, and one for selecting a "default" target
Please see also in the same screen the message I put to help users understand what they need to do "Pick a target for "Finger of Death""

3. **Fix end game**
when the game is finished the game list should refresh

**Comment by Pz1c** [comment]
1 - done

**Comment by Pz1c** [comment]
2 done
