### ISSUE TITLE
Create a new video for Google Play

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#39]
After improving all UI, 
Should create a new video for Google Play listing

**Comment by Prulon** [comment]
@Pz1c 
See [here ](https://drive.google.com/file/d/1fGCJP-ze-MvrbHRzJSw4vHaXjwo_4u1l/view?usp=sharing) a video that I created

**Comment by Prulon** [comment]
@Pz1c 
Please upload the video above and add to Google Play listing 
(I don't want to upload under a personal account)

Also, 
Here's some description I prepared (mostly copy paste from google play)


Install at:
https://play.google.com/store/apps/details?id=net.is.games.WarlocksDuel&referrer=utm_source%3Dyoutube

Warlock's Duel is a free turn based strategy game. Try your spell casting skills to out smart other players online (PvP) or in a single player mode

Players duel in a battle of minds, casting spells at each other, and sometimes bluffing ("Shadow casting").

Warlock spells are text words, where each word like 'SFW' (Summon Goblin) is a spell, and each letter marks a hand gesture ('S' for snap fingers).

Warlocks duel is also known as Spellbinder - the old strategy game that was published by Richard Bartle (1977) about a battle between two wizards (see Wikipedia reference below), and is integrated with the desktop version Waving hands by Ravenblack.

This is an open source project, built by the community.

**Comment by Pz1c** [comment]
Video is amazing! Thanks!! 
https://youtu.be/Kewpe7DD4wI
also added into App Store card
and you added to youtube channel as manager

**Comment by Prulon** [comment]
:)
