### ISSUE TITLE
Sign up screen fixes

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#45]
Looks and works much better.
I had 2 issues:

1. when clicking on the email input, the first letter that I click doesn't get written, so for example when I write idoido@ I only see doido@ . This means that I have to type the first letter twice for it to work
2. The check box doesn't show until it is clicked, and also it looks really really bad after clicking. Can't we just put a checkbox with the regular app color #E7FFFF and have it show like an empty box before click and box with 'V' after click?

**Comment by Pz1c** [comment]
1. suppose first problem related with hard regexp for email validation - it changed  for simple  - hope it's help
2.  
first image V as check indicator and slim border
![image](https://user-images.githubusercontent.com/5511791/119994890-b628d280-bfd5-11eb-9463-0d166253e235.png)
X and bolder border

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/119995491-4f57e900-bfd6-11eb-9bbf-b75a5916106a.png)

**Comment by Pz1c** [comment]
has  problem with two photo in one comment 
or just my local net problem)

**Comment by Prulon** [comment]
This looks good, except there should be a little less space between the checkbox and the text.
Also when the user didn't check the box then the box should be empty. When the box is checked let's put the 'v'

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/120186964-de564280-c21c-11eb-9487-35b771c6c3fe.png)
