### ISSUE TITLE
Fix tutorial

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#47]
Great to see that we have a tutorial :)

Fixes:
1. The entire tutorial messages 1-6 should show on the first turn of the first game. not one per turn. (So basically we have 1 tutorial per game, showing on the first turn of that game, and not spread out in different turns in the same game)
2. Missing the left and right arrows for navigating between the tutorial messages
3. Missing the "Got it!" action at the end of the tutorial
4. The messages should have rounded corners - see in the [wireframes](https://drive.google.com/file/d/1inB1WVvkmr8eyYqUAtIC0F8NwTxsVqU7/view)
5. The last message "You can do similarly more tutorials later on one per game like these:" should be deleted - it is a message from me to you, and not a part of the tutorial :)

**Comment by Prulon** [comment]
btw - once you change the font to Agency FB for the entire app it may be easier to fit in the tutorial texts

**Comment by Pz1c** [comment]
looks like Agency FB applied)
but it's on desktop, hope mobile app will has the same look

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/120189727-5d00af00-c220-11eb-92a1-abc6ac2a3649.png)

**Comment by Pz1c** [comment]
I do the partial fix, you got all hints in first turn but without arrows and button, just click on hint to got next one and hint will be hidden after click on last one
but I one of the next release Ill add arrows and button

**Comment by Pz1c** [comment]
already fixed
