### ISSUE TITLE
Game list screen - text fixes

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#50]
1. 'Start training' --> 'Start Training' with 'T'
2. 'Play against warlock' --> 'Warlock vs. Warlock'
3. If you lose: '<Construct> win!' --> 'Lost vs. <Construct>'
4. If you win: '<MyName> win!' --> 'Won vs. <Construct>'
5. If nobody wins: 'Draw vs. <Construct>'
6. sometimes there's copy that says 'Finished #85967' - why does this happen?, also sometimes there are games with no winner name even though one of the players won
7. When the game is in waiting state, right now it says '1/2' or thing like that --> 'Waiting...'

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/120474306-b697e380-c3b0-11eb-87e2-5e018e072b54.png)
