### ISSUE TITLE
Fix Turn history UI

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#51]
Update the UI of turn history according to this
Notice the following:
1. Font sizes and colors (written in the image)
2. Paddings (written in the image)
3. Background and stars, and glow on left, and padding on left (written in the image)
4. Also note the following about the texts:
- I made the message that you get from the other player in bold
- I removed the texts that are not helpful from the turn history (for example the gesture that the players made)
5. Would be good if it can be closed with 'swipe'. Otherwise it should be closed with 'back' button. No 'apply' and 'cancel' buttons

![image](https://user-images.githubusercontent.com/78275620/120006717-d5c5f800-bfe1-11eb-9235-30ccc08779e6.png)

**Comment by Prulon** [comment]
note: all measure were taken based on size of 600x1068

**Comment by Pz1c** [comment]
what about slider like main menu? 
that's give possibility close with swipe and back button

**Comment by Prulon** [comment]
not really sure what you mean, 
what will it slide? (looks like there's enough space on the screen for all the content)

**Comment by Prulon** [comment]
Don't fix. There's another ticket instead of this
