### ISSUE TITLE
Gesture screen fixes

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#53]
See details in the image, including measurements.
Also see changed behavior in case there's no spell to complete.
Note that spells for completion should include spells other warlock can force you under charm of FFF (if you are under charm or FFF)

![Gesture screen fixes](https://user-images.githubusercontent.com/78275620/120084093-3df60600-c0d6-11eb-8be4-e1c1367f4cf8.jpg)

**Comment by Pz1c** [comment]
split spell list on completed and uncompleted is a great idea 
but it maybe become problem under Charm or Confusion
maybe be better put "Default spell"  instead of "None"?

**Comment by Prulon** [comment]
I think that the best option is that if you are under Charm/Paralysis/Confusion then:
1. The "completed" section should also include all spells that opponent can force you to complete In this case, you would not have "None" because you have other spells (and also Default)
2. Add another line below the "Completed Spells" title, saying "or spells opponent may force"

**Comment by Pz1c** [comment]
almost done
it remains to split the spell list

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/121706878-b4cfcd80-cade-11eb-991a-5ef09698fae6.png)

**Comment by Pz1c** [comment]
mobile will be without scroll bar

**Comment by Prulon** [comment]
Nice!!!
Also note that cards should have a bit more round corners

**Comment by Prulon** [comment]
And not sure if you got correct letter icon size

**Comment by Prulon** [comment]
and notice the glow.png file for the left part :)

**Comment by Pz1c** [comment]
Hard Monday)
But I hope completely close this issue tomorrow

**Comment by Pz1c** [comment]
corners, icon  size, glow.png
still have problem with spell lists and scrolling(
![image](https://user-images.githubusercontent.com/5511791/122061972-adb70100-cdf7-11eb-918c-b124eb063b95.png)
![image](https://user-images.githubusercontent.com/5511791/122062020-b8719600-cdf7-11eb-969f-ff6a5a281ace.png)

**Comment by Pz1c** [comment]
still need fix scrolling and list of complete spells

**Comment by Prulon** [comment]
You should not be able to select "None".
When no spell is complete then no spell is selected, and no '?'

**Comment by Prulon** [comment]
Looks really nice :)

notice the colors of the text:
![image](https://user-images.githubusercontent.com/78275620/122092152-45c1e400-ce12-11eb-96b8-b0ba0b393928.png)

**Comment by Pz1c** [comment]
missed part of logic related with confused/charmed warlock
for faster closing 1.8.9 milestone for confused/charmed warlock show default spell instead of none + list of possible forced spells
