### ISSUE TITLE
Choosing spell target fixes

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#55]
1. When choosing a spell, missing a message saying "Pick a target for <spell name>"
The message should show for 2 seconds and disappear.

![image](https://user-images.githubusercontent.com/78275620/120810499-c6036200-c553-11eb-8247-5bee9a9666e6.png)

2. the possible targets shouldn't have a selection mark boundary around them. Show it only after the user clicks on the target
![image](https://user-images.githubusercontent.com/78275620/120810929-25fa0880-c554-11eb-8da4-98eb67b6fcad.png)

**Comment by Pz1c** [comment]
but after player choose target "Choosing target mode" immediately finish and boundary disappeared

**Comment by Pz1c** [comment]
1. done

**Comment by Prulon** [comment]
The boundary should show "on press", so you would feel like something happened in response to your finger touching it.
(rather than on click when the finger leaves the screen)

**Comment by Pz1c** [comment]
done
