### ISSUE TITLE
Review screen - UI fixes

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#56]
See here:
![image](https://user-images.githubusercontent.com/78275620/120884157-f4cc1780-c5e9-11eb-8b20-31bb95d2bcd4.png)

**Comment by Roeecool** [comment]
I think we can break this task into 2 tasks, and do the first one in this release, and the second in the following release:
1. Show existing list of "reviews", but only change the modal, so it will have the right background, and title, and "Submit"
2. Change the list itself to be more friendly like the images above

**Comment by Prulon** [comment]
I think we can break this task into 2 tasks, and do the first one in this release, and the second in the following release:

Show existing list of "reviews", but only change the modal, so it will have the right background, and title, and "Submit"
Change the list itself to be more friendly like the images above

**Comment by Pz1c** [comment]
@Prulon  please check color for text FEE206 looks too yellow
![image](https://user-images.githubusercontent.com/5511791/132227151-d1995e6e-39c6-49aa-b84b-425bf6f98656.png)

**Comment by Prulon** [comment]
should be FEE2D6 , not FEE206 
('D' instead of '0')

@Pz1c

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/132699460-aebef5f9-41f4-4df1-bac5-b5204581b5d5.png)

**Comment by Prulon** [comment]
Looks great :)

**Comment by Pz1c** [comment]
@Prulon  small question about monster name 
LH:Prioli "unique identifier" but New Monster (R) not
maybe add red and green background? or do not show monster not under control?

**Comment by Pz1c** [comment]
please check experimental naming
![image](https://user-images.githubusercontent.com/5511791/132870424-017c32ba-38fb-4f6a-8771-1e8f6d215860.png)

**Comment by Prulon** [comment]
Looks great :)
Few comments:
1. Cast "at" not "on"
2. Font size should be fixed for all the lines.
3. New monster - I know it is not unique, but I think it is ok. So
LH:Prioli should have the text "New monster (L)" and similarly for right
hand "New monster (R)".
4. On the small icon the text for monster should only be the letter L or R.
Without the words 'new monster'

**Comment by Pz1c** [comment]
aaaaand fix it)
![image](https://user-images.githubusercontent.com/5511791/132873229-83735eac-9d8a-48bd-aece-acc7b67b11aa.png)

**Comment by Prulon** [comment]
1.Cast magic missile at new monster (L)
(Not LH:prulon)

2. Cast at Default target (add the word target)

**Comment by Pz1c** [comment]
and one more
![image](https://user-images.githubusercontent.com/5511791/132875233-aa26458f-3a88-41ce-a6c1-04dd36274cda.png)

**Comment by Prulon** [comment]
Looks good.

Icon sizes and corners are not exactly like in the design but this is less
critical.

Supposed to be 78x60 for letter cards, and letters seem too big.
Monster cards supposed to be 78x78 and more round

**Comment by Pz1c** [comment]
by the way bot server running on mobile 24h) 
but I had no black out, yet) so can't say nothing about stability
but calculation say that mobile should run at least 6 hours and should be to enough for most cases

**Comment by Prulon** [comment]
Sounds great :)

Let me know when there's a new version that I can download. I last
downloaded 1.9.2.7 but didnt open it because I saw you wrote bot only.

Also we need 2 more 5 stars to reach 3.0 :)

**Comment by Pz1c** [comment]
Yep I was afraid taht 1.9.2.7 had bug in orders preview window but it's ok, but ugly)
so you can use it to play

**Comment by Pz1c** [comment]
icon size for gestures decrease
monster icon get a little bit more width)
![image](https://user-images.githubusercontent.com/5511791/133084786-5cb481fe-4954-4990-afe0-62466956e8c7.png)

**Comment by Pz1c** [comment]
and of course each row open related window after click)

**Comment by Prulon** [comment]
Cool, but text should all start at same place, even if icons are different
size

**Comment by Pz1c** [comment]
please check this
![image](https://user-images.githubusercontent.com/5511791/133087853-c6dc4ca7-ae96-4fda-97ab-edc7c98998dc.png)

**Comment by Prulon** [comment]
Cool :)

Text should be cast default spell.
The word spell is missing

**Comment by Prulon** [comment]
Also if no spell is cast then just write "Left hand gesture"  and no "cast
default ..."

**Comment by Pz1c** [comment]
and what text for situation when no spell chooses, but target set?

**Comment by Prulon** [comment]
Like what example?

**Comment by Pz1c** [comment]
for example you can choose some gesture that finish some spell and not choose this spell in list and push button and just choose target
![image](https://user-images.githubusercontent.com/5511791/133091356-98607151-07ef-4693-b68b-4b732c6d27ba.png)
![image](https://user-images.githubusercontent.com/5511791/133091392-5786777d-05af-452b-a538-9b62c103621b.png)

**Comment by Prulon** [comment]
In this case write "cast default spell at..."

The case with no spell is where the spell selection screen says "None".
For example if on the first turn you do a D gesture, which is not a spell.

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/133092322-f4abd17c-d123-4b09-8bd9-0656c3c8df21.png)
![image](https://user-images.githubusercontent.com/5511791/133092501-996d98e1-c13b-4efd-88c1-35ebc9ff9db0.png)

**Comment by Prulon** [comment]
Nice :)))
