### ISSUE TITLE
Blocker bug on sign up

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#59]
See this 1-star review:
"Would love to give it more stars as it seems really fun but when I try to hold down a to put in the @ symbol it removes the entire thing"

my son had the same issue.
He cannot Sign Up. When he tried to put in the '@' in the email the entire string gets erased

**Comment by Pz1c** [comment]
already fixed in 1.8.9
bug should disappeared after release
I'll create build today

**Comment by Prulon** [comment]
so do you want to close this issue?

**Comment by Pz1c** [comment]
I suppose to close after release, when I check it really fixed
