### ISSUE TITLE
Fix order of spells 

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#61]
Change the order of spells in all 3 spellbooks as follows:

In the **gesture screen** and **spell selection** screen the order of spells should be like this:
Primary order by number of matched letters
Secondary order by ABC

So for example, if I have 'PS' then the order should be:
**PS**DD
**PS**DF
**PS**FW
**S**D
**S**FW
**S**PFP
**S**PFPSDW
**S**PPc
**S**PPFD
**S**SFP
**S**WD
and then all the other spells by ABC

The following should be the order of spells in the **main spellbook**, and each section should have a small blue title

Disruptions:
DPP, 
DSF, 
FFF, 
SWD
PSDD, 
PSDF
SPFP
<line break>

Damaging:
'>, 
SD, 
WFP, 
WPFD
WDDc,
DFFDD, 
FSSDD, 
PWPFSSSD
<line break>

Healing:
DFW, 
DFPW
<line break>

Monsters:
SFW
PSFW
FPSFW
WFPSFW
<line break>

Protection:
P, 
p, 
WWP
<line break>

Counters:
cw, 
cDPW, 
WPP, 
WWS, 
PDWP
<line break>

Advanced Enchantments:
PPws, 
DWFFd, 
DWFWd, 
SPPc, 
SPPFD, 
PWPWWc 
DSFFFc, 
DWWFWD
DWSSSP, 
SPFPSDW
<line break>

Elements:
SSFP, 
WWFP
WSSc, 
SWWc
cSWWS, 
cWSSW

**Comment by Prulon** [comment]
Note: right now some of the spells look grey (like Resist Cold), they shouldn't. All spells should be of same color

**Comment by Pz1c** [comment]
grey for "not simple" spells and white for simple  #14
grouping spell is great idea
ordering is also cool
now spells order by internal rank calculated by AI according to current battle situation
but you are right for full spell book better get grouped and alphabetically ordered spells

**Comment by Pz1c** [comment]
spellbook  window from main screen
![image](https://user-images.githubusercontent.com/5511791/124729590-3fa6bb00-df19-11eb-9022-fa87fd5a2c39.png)

**Comment by Prulon** [comment]
Nice!
Missing a big title: "Spellbook"
Also please remove the warlock hat icon

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/124753953-47bf2480-df32-11eb-9669-908a2bb9cf20.png)

**Comment by Pz1c** [comment]
or you mean this title
![image](https://user-images.githubusercontent.com/5511791/124754423-e186d180-df32-11eb-91b5-a9fc677c95d8.png)

**Comment by Prulon** [comment]
Yes, but it should show with same padding etc as the spell description modal

**Comment by Pz1c** [comment]
yep it was only for simplifying explanation

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/124773650-ce313180-df45-11eb-976e-e016d0378b2c.png)

**Comment by Prulon** [comment]
There's something a bit off with the line breaks.
You should have a line break before every title, for example before the "Healing" "Damaging" etc'

@Pz1c

**Comment by Pz1c** [comment]
please check
![image](https://user-images.githubusercontent.com/5511791/124877764-1303a980-dfd4-11eb-847f-68fb3cbfbab9.png)

**Comment by Prulon** [comment]
Looks good!
