### ISSUE TITLE
icons for default target and no target

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#62]
1. Right now the icon sizes for submit default target and for no target are too large, see image. 
2. If possible, then let's align the 'no target' to the left of the screen (under the elemental), instead of close to the 'default target'

![Screenshot_20210619-195815](https://user-images.githubusercontent.com/78275620/122652243-71143e00-d146-11eb-88fe-b65765d7a56b.jpg)

**Comment by Pz1c** [comment]
what about moving Nobody to the left side in place of elemental (when Elemental not exists), and moving some righter when Elemental appear?
icon's size decreased to 60 + 15 padding from top (for usual sizes)
without elemental
![image](https://user-images.githubusercontent.com/5511791/123103612-dc0f8e80-d43e-11eb-8f72-1bd700c9d9b1.png)
with elemental
![image](https://user-images.githubusercontent.com/5511791/123104247-72dc4b00-d43f-11eb-8186-0c213a8bc6c3.png)

**Comment by Prulon** [comment]
Let's go with that, just pay attention that the size of the icons is wrong - the box backgrounds are too small. Notice the X next to the fire elemental - the boxes should be of the same size

@Pz1c

**Comment by Pz1c** [comment]
oh now I understand what you mean under icon size just icon not whole button

**Comment by Pz1c** [comment]
icon size decreased to 60px
![image](https://user-images.githubusercontent.com/5511791/123237430-59420e80-d4e6-11eb-8af8-8fbdea25868b.png)

**Comment by Prulon** [comment]
Looks good :)
