### ISSUE TITLE
Fix tutorial

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#63]
See image below:
1. the tutorial text should cover most of the width of the screen. Leave padding of 24px on each side (and 18px from bottom)

2. Add '<', '>' arrows (except on first tip in row which doesn't have '<', and last that has 'got it!' instead of '>')

3. Padding for the '<' should be 18px from left 

![image](https://user-images.githubusercontent.com/78275620/122652511-fc420380-d147-11eb-8c0a-fe9f0ea4bd42.png)

**Comment by Prulon** [comment]
Let's also change the colors of the tutorial to make it more clear that this is a helper text:
Text color #210430 (dark purple)
Background color #FEE2D6 (cream)

**Comment by Pz1c** [comment]
first and last tutorial message
![image](https://user-images.githubusercontent.com/5511791/123239217-d28e3100-d4e7-11eb-9e8d-398ba0c8e8fb.png)
![image](https://user-images.githubusercontent.com/5511791/123239265-dde15c80-d4e7-11eb-86cf-bfc8e53fdc14.png)

**Comment by Prulon** [comment]
Why are arrows so small?

**Comment by Prulon** [comment]
All in all looks great except for the size of the arrows and the size of "got it"

**Comment by Pz1c** [comment]
please check new version
![image](https://user-images.githubusercontent.com/5511791/123420833-b9a77d80-d5c4-11eb-8faa-6d7295ce8e14.png)
![image](https://user-images.githubusercontent.com/5511791/123421085-11de7f80-d5c5-11eb-87d8-b1b0bb9fccc9.png)

**Comment by Prulon** [comment]
Looks good. Got it should have underline

**Comment by Pz1c** [comment]
aaaaaaand finish)
![image](https://user-images.githubusercontent.com/5511791/123755637-c843ac80-d8c4-11eb-8226-b89e84d7c26f.png)
