### ISSUE TITLE
Spell descriptions fixes

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#64]
Spell description:
1. Add a line break between the short description and the details
2. Spell description should take the whole screen
3. No 'cancel' button
4. Android back should go back, and also add a '<- back' button
5. Background should be the same gradient blue as the spellbook (with stars)
6. See more details below

Do similar fixes for the main spellbook:
1. Make Full screen
2. Add back button and functionality. Remove 'cancel' button
3. Use same padding, and colors for the word 'Spellbook'

![image](https://user-images.githubusercontent.com/78275620/122653814-f9e3a780-d14f-11eb-9b3e-534fa6795e2c.png)

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/123797776-34d3a100-d8ef-11eb-880b-5d76303eddc0.png)

**Comment by Pz1c** [comment]
(fix size for title and short description)
![image](https://user-images.githubusercontent.com/5511791/123798413-d3600200-d8ef-11eb-81ca-ee639633cb33.png)

**Comment by Pz1c** [comment]
also set transparent bg for "Back" button
![image](https://user-images.githubusercontent.com/5511791/123803656-27211a00-d8f5-11eb-89b7-f950e5797d4d.png)

**Comment by Prulon** [comment]
Hmm, I think you made the back smaller instead of making the short
description bigger

**Comment by Prulon** [comment]
Ahh, no, the short is ok, but the back seems smaller now, no?

**Comment by Pz1c** [comment]
back button text and short description text should be same size on prev image
but in this pic I make back button text a bit large (30 instead of 24)
please check
![image](https://user-images.githubusercontent.com/5511791/123810433-0eb3fe00-d8fb-11eb-8b4e-60f9cb2f8051.png)

**Comment by Prulon** [comment]
This doesn't look quite right.

Basically in the original wireframe I had:
Spell name size = 42 (same size as 'Start Training' button on main screen)
Spell short description = 'back' = 'Details' title = 28 (same as "Your Games:" on main screen)
I also had the full details text in 28, but we can change to 21 (same as the tutorial text size)

Also, there should be 1 empty line between the short description and the 'Details' title

**Comment by Pz1c** [comment]
thanks for Font formula (63:42:28:21) GUI development is not my better skill)
(hard day was today, has a small bit of time for game dev, but Ukraine in 1/4 Euro2020 )
please check new version (long desc font size decreased to 21 because paralyze text too long)
fff
![image](https://user-images.githubusercontent.com/5511791/123968392-da564580-d9bf-11eb-943d-89f2b1caeeba.png)
swd
![image](https://user-images.githubusercontent.com/5511791/123969246-b6dfca80-d9c0-11eb-884b-8f990bd9ec4f.png)

**Comment by Prulon** [comment]
Looks good and congrats :)

**Comment by Pz1c** [comment]
thanks) looks like our team gain a lucky ticket))
