### ISSUE TITLE
Update waiting for turn modal, similarly to spell description modal

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#66]
![image](https://user-images.githubusercontent.com/78275620/122991760-10873a00-d3ae-11eb-95b5-031dac45c6f6.png)

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/124773202-67ac1380-df45-11eb-8218-6592fdd0b497.png)

**Comment by Pz1c** [comment]
force button appear in 2 days)

**Comment by Prulon** [comment]
Cool

**Comment by Prulon** [comment]
Instead of RH and LH write "Right hand" and "Left hand"

@Pz1c

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/124876875-28c49f00-dfd3-11eb-90d7-16fed0621ec8.png)

**Comment by Prulon** [comment]
Great!
