### ISSUE TITLE
Update warlock modal, similarly to spell description modal

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#67]
![image](https://user-images.githubusercontent.com/78275620/122992972-68727080-d3af-11eb-8dac-b254b645e5a9.png)

**Comment by Pz1c** [comment]
check this ;) all sizing same as in spell description 
![image](https://user-images.githubusercontent.com/5511791/124267728-51ffae00-db41-11eb-8180-b4cfb62640c4.png)

**Comment by Prulon** [comment]
Nice! Looks good. But let's have the 'Life' in regular font size.
We did the extra small one in spell description just because there was too
much text there

**Comment by Pz1c** [comment]
increase font text to 28
![image](https://user-images.githubusercontent.com/5511791/124280397-4e742300-db51-11eb-83e7-9a75d9dfdcbc.png)

**Comment by Prulon** [comment]
Looks good!
