### ISSUE TITLE
Update monster modal, similarly to spell description

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#68]
![image](https://user-images.githubusercontent.com/78275620/122994464-2b0ee280-d3b1-11eb-824e-39f7cb88628d.png)

**Comment by Pz1c** [comment]
hope this will fine with first attempt)
![image](https://user-images.githubusercontent.com/5511791/124280477-63e94d00-db51-11eb-910b-c97d01181d63.png)
