### ISSUE TITLE
Update ended game history modal, similarly to spell description modal

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#69]
![image](https://user-images.githubusercontent.com/78275620/122995552-6bbb2b80-d3b2-11eb-93b2-acb88fe5cb85.png)

**Comment by Pz1c** [comment]
first version without coloring
![image](https://user-images.githubusercontent.com/5511791/125035750-de0e5a00-e09a-11eb-8f4c-d6ed664d11e4.png)

**Comment by Prulon** [comment]
Looks good.
Can we remove from the list all the items of the form: Galbarad proffers the palm of his left hand
(meaning remove all gesture lines)

Let's push 1.9.0 live :)

**Comment by Prulon** [comment]
Also, we need to fix the summary line - 
right now it is "Turn 19 in Very Friendly bla bla..."

Instead it should be:
"Construct is Victorious!" 
(so putting the last line in the turn history)
also if someone surrenders or dies let's put that in the summary too, so we will have:
"Construct surrenders. Galbarad is Victorious"

@Pz1c

**Comment by Pz1c** [comment]
please check
![image](https://user-images.githubusercontent.com/5511791/125060239-d360be80-e0b4-11eb-9494-a3ab7a48e7fb.png)

**Comment by Prulon** [comment]
Looks good!

**Comment by Prulon** [comment]
I just finished a game and the modal looks very different than the image above.
Here's the strange behavior:
1. The modal that I see immediate when the game ends looks different
2. However, when I click on the game that ended afterwards, then I see the modal correctly.

**Comment by Pz1c** [comment]
fixed

**Comment by Pz1c** [comment]
fixed
