### ISSUE TITLE
Review, Prioli

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#7]
Games list:
1. Refresh should close the panel and show an updated list of games
2. Scrolling up the main screen should also refresh it
3. When clicking "new game" should automatically join a random Friendly game, from all the open games of users with Elo +- 100. Only if there's no game to join then a new game should be created.
4. When playing a new game with a bot it doesn't really start right away, and needs to refresh. So - should auto refresh it after a few seconds to see if it starts (and maybe show a loader). Ideally we would put here the modal that I created. 
5. Main CTA (call to action) - better do the following:
- For players with ELO 1500 or less, the main button should be "Training Game" (= play with bot) and the secondary should be New Game
- For players with ELO >1500 should be like it is now

Game screen:

1. Review - remove the "are you sure"
2. Elementals don't show on the screen when summoned
3. When the battle is over you see an "Error" message, instead of showing that the game is finished

Gesture screen

1. After picking a letter, should only show spells that can actually be completed this turn, including also spells that can be completed with other letters (because of possible charm effects). For example after WW, if a player picks P then the available spells should be WWP, Default, WWS
2. Second picking the '>' should be able to pick a target 
3. When picking '>' it doesn't show as '>' on the battle screen, instead it shows blank
4. After picking "default" spell it should also be possible to pick a target. This is important when you are under charm for example, so you may still want to have the default spell, but you'd want to pick a target.
5. In Amnesia you should only be able to pick the last letters
6. In Maladroit you should be able to pick P/P and surrender
7. In Maladroit when you pick letters for any hand this should also change the letter for the other hand
8. After clicking on the same gesture again it should get unselected. For example, I have 'WW' I click P, I see the list of relevant spells, then I click P again. What should happen is that P gets unselected and I see all spellbook

Spellbook
1. Better split the spellbook to 2 parts. Basic and Advanced. This way it would be simpler for beginners.
- you can put a label "advanced" before the advanced spells.
- I would put the following as "basic": 
DFW, DPP, DSF, FFF
P, p, >
PSDF, PSDD, PSFW
SD, SFW, SWD
WFP, WPFD, WWP, WWS, WPP

**Comment by Pz1c** [comment]
splitted on small issues
