### ISSUE TITLE
Get Feedback

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#70]
Goal: start getting some initial user feedback so we need what we need to improve, and hopefully later ask people to share and rate the game.

Tasks:
1. Add a new entry to the main menu called: "Feedback"
2. Clicking on it will open the screen below (very similar to the spell description and other modals we have). Except that it should not have the "skip" action.
3. Clicking on "Send Feedback" should open a Google form (unless you have a better idea) asking users 3 questions: A) "How is your experience so far?" (1=bad, 5=great). B) "What do you like so far?" (open question) C) "What should we improve?" (open question). (We should probably open the form in a browser...). Note: after clicking the "Send" the modal should close.
4. The same modal should also when players start their 3rd game. Start the new game in the background, and then show the modal. In this case also include the "skip" action, allowing users to continue without feedback. No matter if the users click "skip" or "Send feedback" the game should be started, except that with "Send Feedback" they will get the form on a browser.

![image](https://user-images.githubusercontent.com/78275620/123508584-f7fe7480-d678-11eb-9c0a-6e577b5968ad.png)

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/136192374-f3872105-94ab-429d-b272-3e585526c6fd.png)
