### ISSUE TITLE
Add animations

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#74]
Add animations at the beginning of the turn.
See the following GIF and list of frames:
1a. All greyed (20ms)
1b. Player says message - until click '>'

2a. All greyed (20ms)
2b. Warlock casts spell summon (bright SFW + message) (20ms)
2c. Warlock casts spell summon (bright SFW + message + highlight spell) - until click '<' or '>'

3a. All greyed, keep goblin (20ms)
3b. Warlock casts spell shield (bright 'P' + message, and keep the goblin) (20ms)
3c. Warlock casts spell shield (bright 'P' + message, and keep the goblin + highlight spell) - until click '<' or '>'

4a. All greyed, keep goblin and shield (20ms)
4a. Goblin attacks (highlight goblin + message, keep all previous spells) (20ms)
4b. Goblin attacks (highlight goblin + message, keep all previous spells + highlight target) - until click '<' or 'Got it!'

5a. (missing from GIF) All greyed, keeping only spells and monsters that remain (so keep goblin, but remove shield) (20ms)
5b. Show active cards (20ms)
5c. Show active cards + next turn gestures. Turn begins

Notes: 
A) I didn't put the '<' and '>' and 'Got it!' on the messages in the GIF, but they should be there like the tutorial.
B) The color of text in all messages is #210430
C) The background of the text in the messages is: #E7FFFF for what warlocks say, #10C9F5 for spells they cast, #FEE2D6 for attacks
D) The background of highlighted spells (in 2c, 3c) is #10C9F5 (I didn't do it correctly in the GIF)
E) The background of the attacker and the target (in 4b, 4c) is #FEE2D6

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/78275620/123522120-0160fe80-d6c4-11eb-8038-f70dc9f603cf.gif)

**Comment by Pz1c** [comment]
oh it's really cool
I'll try to do this soon

**Comment by Roeecool** [comment]
Clarification about other effects:
1. Spell has effect (like "Construct's left hand is paralyzed") --> highlight the spell (background #10C9F5), show message with background #10C9F5. Note: at this point let's not add additional animation here for showing which hand is affected etc'

2. For messages like the following don't show the message, and don't put an animation:
"Prulon waves his left hand." or
"Nasty Goblin is summoned to serve Prulon", or 
"Prulon starts to lose coordination." or 
"superchig is covered by a shimmering shield." or
"Prulon directs Stinking Ogre to attack the monster superchig is summoning with his left hand."

3.  For messages like 
"Stinking Ogre swings wildly for the monster superchig is summoning with his left hand, but misses."
treat this message like any attack. So background for the monster and the text is #FEE2D6

4. At the end of the game, show the animation before existing the game. Only after you click on the last animation then go back to the game list screen (and no extra modal is needed). In that case show the following messages animations:
"superchig surrenders."  only text. background #FEE2D6
"Prulon is victorious!" only text. background #E7FFFF

**Comment by Prulon** [comment]
Clarification about other effects:

Spell has effect (like "Construct's left hand is paralyzed") --> highlight the spell (background #10C9F5), show message with background #10C9F5. Note: at this point let's not add additional animation here for showing which hand is affected etc'

For messages like the following don't show the message, and don't put an animation:
"Prulon waves his left hand." or
"Nasty Goblin is summoned to serve Prulon", or
"Prulon starts to lose coordination." or
"superchig is covered by a shimmering shield." or
"Prulon directs Stinking Ogre to attack the monster superchig is summoning with his left hand."

For messages like
"Stinking Ogre swings wildly for the monster superchig is summoning with his left hand, but misses."
treat this message like any attack. So background for the monster and the text is #FEE2D6

At the end of the game, show the animation before existing the game. Only after you click on the last animation then go back to the game list screen (and no extra modal is needed). In that case show the following messages animations:
"superchig surrenders." only text. background #FEE2D6
"Prulon is victorious!" only text. background #E7FFFF

**Comment by Pz1c** [comment]
I suppose we need some settings to allow switch off animation for advanced users

**Comment by Prulon** [comment]
Sounds good.
I think we would always want to show the "say" but can add setting to
1. On/off animation text bubbles
2. On/off animation actions

Let's start as is, and decide later if settings are needed for 1 and/or 2

**Comment by Pz1c** [comment]
I propose move animation to 1.9.5 cause this issue need a lot of changes in wnd_battle same as issues from 1.9.5

**Comment by Prulon** [comment]
Ok

**Comment by Prulon** [comment]
Note:
In games against Bots don't show the "Say" as part of the animation, otherwise it will be very annoying

**Comment by Pz1c** [comment]
time to do)

**Comment by Pz1c** [comment]
hm looks like commit to master branch with issue id in commit's description auto close this issue)

**Comment by Pz1c** [comment]
as I say task partially complete 
still need todo:
add icons that disappeared during turn (monster that died during turn, cancelled spells, P-shield)

**Comment by Pz1c** [comment]
looks like #209 is the key for completing animation

**Comment by Pz1c** [comment]
will be fixed under #227
