### ISSUE TITLE
Game title for waiting

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#76]
1. For a Waiting game, where other player didn't join the title should change from "Wait #864048" which is now, 
to "Waiting to start..." and no game number

2. When waiting for another player to play his turn the title should be "Waiting for Galbarad..."

**Comment by Pz1c** [comment]
@Prulon  please check
![image](https://user-images.githubusercontent.com/5511791/124628527-3b32c180-de89-11eb-8840-1b85cf8c55d9.png)

**Comment by Prulon** [comment]
Please remove the 2/6

**Comment by Pz1c** [comment]
fixed
also I change ordering started goes first
![image](https://user-images.githubusercontent.com/5511791/124707133-1417d680-df01-11eb-82f7-202cedcbfaa7.png)

**Comment by Prulon** [comment]
Cool!

**Comment by Prulon** [comment]
I see a different title for the waiting games: 
I see "Waiting for 1/2..." 
and "Waiting for superchig 2/2..."
for games that didn't start yet.

Instead it should say "Waiting to start..."

**Comment by Pz1c** [comment]
1/2 - old artifact should not appear for a new battles
"Waiting for superchig 2/2..." - shows for game with undefined status, try to open this games and push refresh 
title should become "Waiting to start..."
