### ISSUE TITLE
Move "refresh" to main game screen

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#78]
1. Remove the "Refresh" from the main menu.
2. Add to main screen, see below, with padding 24px from right (same as for "Your Spells"), color #A8F4F4

![image](https://user-images.githubusercontent.com/78275620/124363643-282faf80-dc45-11eb-9d39-2f6576dfe00a.png)

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/124429257-506afb80-dd76-11eb-8334-68a911890d01.png)
