### ISSUE TITLE
Add option to invite a friend when creating a new game

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#79]
Add a modal when creating a new game or when clicking training mode. (see one version for each in the image).

When clicking "Start Training":
1. Clicking on "Bot" is the same as today
2. Clicking on "Friend" will start the "invite a friend" process, sending an invite link. The game to be invited to is a **"Very Friendly"**

When in clicking "New Game":
1.  Clicking "Random" will start a new random game as today
2.  Clicking on "Friend" will start the "invite a friend" process, sending an invite link. The game to be invited to is a **"Friendly"**

![image](https://user-images.githubusercontent.com/78275620/124373735-999b4c80-dc9d-11eb-96d5-e6c3e5e5a59e.png)

**Comment by Prulon** [comment]
Updated texts

![image](https://user-images.githubusercontent.com/78275620/132059535-d7174e31-4a47-4237-8173-e4d7b3e05e4d.png)
![image](https://user-images.githubusercontent.com/78275620/132059551-8f662741-b090-43d4-8fb2-67192deebe8b.png)

**Comment by Pz1c** [comment]
dependent on #105

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/145212998-11368827-359e-42e4-a72d-9c843e69e82e.png)
