### ISSUE TITLE
Get 9 more people to submit 5-star reviews, and reach 3.0 rating

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#81]
Get friends / family to submit 5 star reviews

**Comment by Pz1c** [comment]
lets do it!

**Comment by Prulon** [comment]
Got another 5-star from a friend.
7 more to go

**Comment by Prulon** [comment]
Looks like we've made progress on this, and we now need 4 more to go to reach 2.97 which will show as 3 stars

**Comment by Prulon** [comment]
3 more to go till 3 stars

**Comment by Pz1c** [comment]
looks like we will get good ration soon, because our latest ranks are high
https://www.androidauthority.com/play-store-ratings-2739066/

**Comment by Prulon** [comment]
Probably not so good for us. 
It's going to show the average per country which right now looks like this for some of the main countries:
The good news is that old low scores from non EN languages will not affect EN, so we don't need that many good scores to go up

![image](https://user-images.githubusercontent.com/78275620/134779749-af746e15-850c-4c99-a63a-963480994cec.png)

**Comment by Prulon** [comment]
@Pz1c 
Did you see we got a new 5* yesterday from Czech republic?

**Comment by Pz1c** [comment]
![Screenshot_20220329-141029_Play Console](https://user-images.githubusercontent.com/5511791/160599039-55e41845-fc7a-4fe2-b368-9bbe418c3794.jpg)
