### ISSUE TITLE
Add a waiting for game modal, similar to game description modal

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#83]
Waiting Modal

![image](https://user-images.githubusercontent.com/78275620/125137693-e22b8d80-e115-11eb-9231-659f6e2f84ce.png)

**Comment by Pz1c** [comment]
I add a little bit info
![image](https://user-images.githubusercontent.com/5511791/125602396-01c1a34c-b437-44e6-b99d-3e9afd018465.png)

**Comment by Prulon** [comment]
Cool

**Comment by Prulon** [comment]
Small comments about the text:
1. The title should be "Waiting to start" and not "Waiting for start"
2. In the extra text write:
Warlocks waiting in the circle: Dubber
Waiting for: 4 warlocks

@Pz1c

**Comment by Pz1c** [comment]
done
