### ISSUE TITLE
spellbook fixes

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#84]
1.9.0 looks great so far, but I've found the following issues:

1. In the spell book, there's a scrolling issue when you click on a spell. It seems that the text can move to the left/right, and it shouldn't.
2. DFWFd - the spell name and descriptions are wrong (showing key instead of text)
3. Shield - missing the spell icon (the purple shield)
4. time stop - the icon is empty
5. disease - the icon is empty
6. clap of lightning - the spell short description is wrong (showing key instead of text)
7. I think it would be good to make the text size of the long spell descriptions smaller (So use our size 21px from our range 63:42:28:21)
8. When selecting a gesture the order of spells should be by ABC, and no spells should be grey
9. When selecting a gesture, it seems like there's an issue with the scroll. It is quite hard to scroll the spellbook

**Comment by Pz1c** [comment]
1. -
2. +
3. +
4. +
5. +
6. +
7. +
8. -
9. -

**Comment by Prulon** [comment]
Looked at this again and I see:
2, 3, 4, 5, 6, 7 - fixed
1, 8, 9 - not fixed (I have 1.9.0.5 version installed)

---------------
About #8 - I'm having second thoughts.
I think it would be better in the gesture selection to have the same order as in the main spell book, meaning show:
"Disruptions:
DPP
DSF
etc;

Damaging:
>
SD
etc;"

and when you already select a gesture like 'D' then we could have the order be alphabetically.
This will make it easier for Newbies to learn the spells and not feel like there are too many. Makes sense?


------------
Also, in the main spell book, the name and gestures of the DFWFd spell show wrong. 
'DWFWd         DWFWd' ---> shows now
'DFWFd          Blindness'  ----> should be

**Comment by Pz1c** [comment]
8. will be fixed in 1.9.2

**Comment by Pz1c** [comment]
1 . should be fixed in 1.9.2 (I hope)

**Comment by Pz1c** [comment]
9. will bi fixed under #102

**Comment by Prulon** [comment]
@Pz1c 


about 8 - did you see my comment above?

This is what I wrote:
I think it would be better in the gesture selection to have the same order as in the main spell book, meaning show:
"Disruptions:
DPP
DSF
etc;

Damaging:

SD
etc;"

and when you already select a gesture like 'D' then we could have the order be alphabetically.
This will make it easier for Newbies to learn the spells and not feel like there are too many. Makes sense?

**Comment by Pz1c** [comment]
oh miss it sorry(
move it to separated issue #104
