### ISSUE TITLE
Select a target - fixes

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#85]
1. Seems that the size of the square and the corners for "No Target" and "Default Target" are not the same as for all the other squares (like the heart). It seems that the corners are more round, and the square looks smaller

2. Let's also change the colors of the toast that says "Select a target for default spell" to be the same as in the tutorial, meaning:
Text color #210430 and background color #FEE2D6

3. Let's make the toast show for a bit less time, maybe 0.5seconds less

**Comment by Pz1c** [comment]
should be fixed in 1.9.0.4
