### ISSUE TITLE
Refresh text size

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#86]
The size of the text "Refresh" on the main screen should be the same as for the action below the main button 
("Start Training" if you have the "New Game" button)

**Comment by Pz1c** [comment]
sorry dont get it(
it's looks like same size 
![image](https://user-images.githubusercontent.com/5511791/125171714-34c08480-e1be-11eb-9fea-40df0cc2e2ce.png)

but on mobile start training looks smaller i'll try to fix

**Comment by Pz1c** [comment]
should be fixed in 1.9.0.4
