### ISSUE TITLE
Fix text size of "I am 13+ years old"

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#87]
Right now this text ("I am 13+ years old") is huge.
It should be the same size as the word "Password" or "Email"
Also, please add a small space between the box and the "I am ..." they are too close together.

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/125171404-c16a4300-e1bc-11eb-831f-ef8cc89ad61a.png)

**Comment by Prulon** [comment]
Cool, please add some space between the checkbox and the text
@Pz1c

**Comment by Pz1c** [comment]
please check 
![image](https://user-images.githubusercontent.com/5511791/125255861-883cea80-e304-11eb-8361-6104b4a80868.png)

**Comment by Prulon** [comment]
Looks good
