### ISSUE TITLE
New Game Error Modal

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#89]
See below.
Link "Learn More" should go to https://games.ravenblack.net/rules/0/register.html

![image](https://user-images.githubusercontent.com/78275620/125141453-c330f980-e11d-11eb-9649-ba3d8e0a9edc.png)

**Comment by Pz1c** [comment]
![image](https://user-images.githubusercontent.com/5511791/125596038-ed92fbef-e67a-48ff-8a73-dacb2f7318e9.png)

**Comment by Pz1c** [comment]
please check)

**Comment by Prulon** [comment]
Cool
