### ISSUE TITLE
Bug on Completed spells

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#95]
Do the following:
1. Submit gestures for first turn, for example 'S' and 'W'
2. On second turn submit 'P' on one or both hands

Expected result:
Show that "Shield" and/or 'Surrender' are completed (note that for surrender the spell you cast is still a shield)

Actual result:
You only see "None" in the completed spells list

**Comment by Pz1c** [comment]
Shield - fixed, but still problem with both handed spells
